/**
 * Values of `data.property.type`, derived from Basic Land and Property Unit (BLPU) classification codes
 */
export const PropertyTypes = {
  commercial: 'Commercial',
  'commercial.agriculture': 'Agricultural',
  'commercial.agriculture.farm': 'Farm / Non-Residential Associated Building',
  'commercial.agriculture.horticulture': 'Horticulture',
  'commercial.agriculture.horticulture.vineyard': 'Vineyard',
  'commercial.agriculture.horticulture.watercress': 'Watercress Bed',
  'commercial.agriculture.land':
    'Agricultural - Applicable to land in farm ownership and not run as a separate business enterprise',
  'commercial.agriculture.land.crops': 'Permanent Crop / Crop Rotation',
  'commercial.agriculture.land.grazing': 'Grazing Land',
  'commercial.agriculture.land.orchard': 'Orchard',
  'commercial.animals': 'Animal Centre',
  'commercial.animals.equestrian': 'Equestrian',
  'commercial.animals.equestrian.racing': 'Horse Racing / Breeding Stable',
  'commercial.animals.equestrian.riding': 'Commercial Stabling / Riding',
  'commercial.animals.kennelsCattery': 'Cattery / Kennel',
  'commercial.animals.sanctuary': 'Animal / Bird / Marine Sanctuary',
  'commercial.animals.sanctuary.animals': 'Animal Sanctuary',
  'commercial.animals.sanctuary.marine': 'Marine Sanctuary',
  'commercial.animals.services': 'Animal Services',
  'commercial.animals.services.grooming': 'Pet Grooming Salon',
  'commercial.animals.services.quarantine': 'Animal Quarantining',
  'commercial.animals.vet': 'Vet / Animal Medical Treatment',
  'commercial.community': 'Community Services',
  'commercial.community.HWRC': 'Public Household Waste Recycling Centre (HWRC)',
  'commercial.community.cemetery':
    'Cemetery / Crematorium / Graveyard. In Current Use.',
  'commercial.community.cemetery.cemetery': 'Cemetery',
  'commercial.community.cemetery.chapelOfRest': 'Chapel Of Rest',
  'commercial.community.cemetery.columbarium': 'Columbarium',
  'commercial.community.cemetery.crematorium': 'Crematorium',
  'commercial.community.cemetery.military': 'Military Cemetery',
  'commercial.community.court': 'Law Court',
  'commercial.community.employment': 'Job Centre',
  'commercial.community.hall':
    'Public / Village Hall / Other Community Facility',
  'commercial.community.hall.club': 'Youth Recreational / Social Club',
  'commercial.community.prison': 'Prison',
  'commercial.community.prison.detention': 'HM Detention Centre',
  'commercial.community.prison.secureResidential':
    'Secure Residential Accommodation',
  'commercial.community.prison.service': 'HM Prison Service',
  'commercial.community.recycling': 'Recycling Site',
  'commercial.community.religious':
    'Church Hall / Religious Meeting Place / Hall',
  'commercial.community.scoutHut': 'Scout hut',
  'commercial.community.services': 'Community Service Centre / Office',
  'commercial.community.wc': 'Public Convenience',
  'commercial.education': 'Education',
  'commercial.education.college': 'College',
  'commercial.education.college.further': 'Further Education',
  'commercial.education.college.higher': 'Higher Education',
  'commercial.education.nursery': 'Children’s Nursery / Crèche',
  'commercial.education.other': 'Other Educational Establishment',
  'commercial.education.school':
    'Preparatory / First / Primary / Infant / Junior / Middle School',
  'commercial.education.school.boarding': 'Boarding School',
  'commercial.education.school.first': 'First School',
  'commercial.education.school.infant': 'Infant School',
  'commercial.education.school.junior': 'Junior School',
  'commercial.education.school.middle': 'Middle School',
  'commercial.education.school.primary.private':
    'Non State Primary / Preparatory School',
  'commercial.education.school.primary.state': 'Primary School',
  'commercial.education.school.secondary': 'Secondary / High School',
  'commercial.education.school.secondary.private': 'Non State Secondary School',
  'commercial.education.school.secondary.state': 'Secondary School',
  'commercial.education.specialNeeds': 'Special Needs Establishment',
  'commercial.education.trainingCentre': 'Training Centre',
  'commercial.education.university': 'University',
  'commercial.emergency': 'Emergency / Rescue Service',
  'commercial.emergency.air': 'Air Sea Rescue / Air Ambulance',
  'commercial.emergency.ambulance': 'Ambulance Station',
  'commercial.emergency.coastguard': 'Coastguard Rescue / Lookout / Station',
  'commercial.emergency.fireCommandCentre': 'Fire command centre',
  'commercial.emergency.fireStation': 'Fire Station',
  'commercial.emergency.fireTraining': 'Fire Service Training',
  'commercial.emergency.lifeboat': 'Lifeboat Services / Station',
  'commercial.emergency.lifeguard': 'Lifeguard Facility',
  'commercial.emergency.lighthouse': 'Lighthouse',
  'commercial.emergency.mountain': 'Mountain Rescue Station',
  'commercial.emergency.policeBox': 'Police Box / Kiosk',
  'commercial.emergency.policeStation': 'Police / Transport Police / Station',
  'commercial.emergency.policeTraining': 'Police Training',
  'commercial.fish': 'Fishery',
  'commercial.fish.farm': 'Fish Farming',
  'commercial.fish.hatchery': 'Fish Hatchery',
  'commercial.fish.oysters': 'Oyster / Mussel Bed',
  'commercial.guest': 'Hotel / Motel / Boarding / Guest House',
  'commercial.guest.hostel':
    'Boarding / Guest House / Bed And Breakfast / Youth Hostel',
  'commercial.guest.hostel.youth': 'Youth Hostel',
  'commercial.guest.hotel': 'Hotel/Motel',
  'commercial.guest.shortLet':
    'Holiday Let/Accomodation/Short-Term Let Other Than CH01',
  'commercial.industrial':
    'Industrial Applicable to manufacturing, engineering, maintenance, storage / wholesale distribution and extraction sites',
  'commercial.industrial.abattoir': 'Slaughter House / Abattoir',
  'commercial.industrial.buildersYard': 'Builders’ Yard',
  'commercial.industrial.carbonisation':
    'Coke works and other coal carbonisation plants',
  'commercial.industrial.extraction': 'Mineral / Ore Working / Quarry / Mine',
  'commercial.industrial.extraction.distribution':
    'Mineral Distribution / Storage',
  'commercial.industrial.extraction.mining': 'Mineral Mining / Active',
  'commercial.industrial.extraction.oilGas': 'Oil / Gas Extraction / Active',
  'commercial.industrial.extraction.processing': 'Mineral Processing',
  'commercial.industrial.extraction.quarrying':
    'Mineral Quarrying / Open Extraction / Active',
  'commercial.industrial.extraction.quarrying.sandOrGravel':
    'Sand and gravel working',
  'commercial.industrial.filmProcessing':
    'Film and photographic processing works',
  'commercial.industrial.fishProcessing': 'Fish Processing',
  'commercial.industrial.incineration': 'Incinerator / Waste Transfer Station',
  'commercial.industrial.laundry': 'Industrial laundry',
  'commercial.industrial.light': 'Workshop / Light Industrial',
  'commercial.industrial.light.catering': 'Catering premises & production',
  'commercial.industrial.light.garage': 'Servicing Garage',
  'commercial.industrial.light.storage.post': 'Postal Sorting / Distribution',
  'commercial.industrial.maintenanceDepot': 'Maintenance Depot',
  'commercial.industrial.manufacturing': 'Factory/Manufacturing',
  'commercial.industrial.manufacturing.aircraft': 'Aircraft Works',
  'commercial.industrial.manufacturing.beer': 'Brewery',
  'commercial.industrial.manufacturing.boats': 'Boat Building',
  'commercial.industrial.manufacturing.bricks': 'Brick Works',
  'commercial.industrial.manufacturing.cement': 'Cement Works',
  'commercial.industrial.manufacturing.chemicals': 'Chemical Works',
  'commercial.industrial.manufacturing.cider': 'Cider Manufacture',
  'commercial.industrial.manufacturing.dairy': 'Dairy Processing',
  'commercial.industrial.manufacturing.distillery': 'Distillery',
  'commercial.industrial.manufacturing.dyeWorks': 'Dye works',
  'commercial.industrial.manufacturing.engineering': 'Engineering works',
  'commercial.industrial.manufacturing.flour': 'Flour Mill',
  'commercial.industrial.manufacturing.food': 'Food Processing',
  'commercial.industrial.manufacturing.glass': 'Glassworks',
  'commercial.industrial.manufacturing.hops': 'Oast House',
  'commercial.industrial.manufacturing.metal':
    'Metal manufacturing & processing',
  'commercial.industrial.manufacturing.oil': 'Oil Refining',
  'commercial.industrial.manufacturing.ordnance':
    'Ordnance manufacturing & processing',
  'commercial.industrial.manufacturing.other': 'Manufacturing',
  'commercial.industrial.manufacturing.paper': 'Paper Mill',
  'commercial.industrial.manufacturing.pottery': 'Pottery Manufacturing',
  'commercial.industrial.manufacturing.printing': 'Printing Works',
  'commercial.industrial.manufacturing.ships': 'Shipyard',
  'commercial.industrial.manufacturing.steel': 'Steel Works',
  'commercial.industrial.manufacturing.sugar': 'Sugar Refinery',
  'commercial.industrial.manufacturing.textileWorks': 'Textile works',
  'commercial.industrial.manufacturing.timber': 'Timber Mill',
  'commercial.industrial.manufacturing.wine': 'Winery',
  'commercial.industrial.recycling': 'Recycling Plant',
  'commercial.leisure':
    'Leisure - Applicable to recreational sites and enterprises',
  'commercial.leisure.amusements': 'Amusements',
  'commercial.leisure.amusements.pier': 'Leisure Pier',
  'commercial.leisure.arena': 'Arena / Stadium',
  'commercial.leisure.arena.showground': 'Showground',
  'commercial.leisure.arena.stadium': 'Stadium',
  'commercial.leisure.beachHut':
    'Beach Hut (Recreational, Non-Residential Use Only)',
  'commercial.leisure.casino': 'Casino',
  'commercial.leisure.club.private': 'Licensed Private Members’ Club',
  'commercial.leisure.club.social': 'Recreational / Social Club',
  'commercial.leisure.dancehall': 'Dancehall',
  'commercial.leisure.entertainment':
    'Bingo Hall / Cinema / Conference / Exhibition Centre / Theatre / Concert Hall',
  'commercial.leisure.entertainment.cinema': 'Cinema',
  'commercial.leisure.entertainment.concert': 'Concert Hall',
  'commercial.leisure.entertainment.exhibition':
    'Conference / Exhibition Centre',
  'commercial.leisure.entertainment.mixed': 'Entertainment Complex',
  'commercial.leisure.entertainment.theatre': 'Theatre',
  'commercial.leisure.holiday': 'Holiday / Campsite',
  'commercial.leisure.holiday.accommodation': 'Holiday Accommodation',
  'commercial.leisure.holiday.camping': 'Camping',
  'commercial.leisure.holiday.caravanning': 'Caravanning',
  'commercial.leisure.holiday.centre': 'Holiday Centre',
  'commercial.leisure.holiday.holidayHomeSite': 'Holiday home site',
  'commercial.leisure.holiday.youth': 'Youth Organisation Camp',
  'commercial.leisure.iceSkating': 'Ice skating rink',
  'commercial.leisure.library': 'Library',
  'commercial.leisure.library.readingRoom': 'Reading Room',
  'commercial.leisure.museum': 'Museum / Gallery',
  'commercial.leisure.museum.art': 'Art Centre / Gallery',
  'commercial.leisure.museum.aviation': 'Aviation Museum',
  'commercial.leisure.museum.heritage': 'Heritage Centre',
  'commercial.leisure.museum.historicVehicles':
    'Historic Vessel / Aircraft / Vehicle',
  'commercial.leisure.museum.industrial': 'Industrial Museum',
  'commercial.leisure.museum.maritime': 'Maritime Museum',
  'commercial.leisure.museum.military': 'Military Museum',
  'commercial.leisure.museum.science': 'Science Museum',
  'commercial.leisure.museum.transport': 'Transport Museum',
  'commercial.leisure.park.amusement': 'Amusement Park',
  'commercial.leisure.park.aquatic': 'Aquatic Attraction',
  'commercial.leisure.park.model': 'Model Village Site',
  'commercial.leisure.park.wildlife': 'Wildlife / Zoological Park',
  'commercial.leisure.park.zoo': 'Zoo / Theme Park',
  'commercial.leisure.pettingFarm': 'Petting farm',
  'commercial.leisure.sport':
    'Indoor / Outdoor Leisure / Sporting Activity / Centre',
  'commercial.leisure.sport.athletics': 'Athletics Facility',
  'commercial.leisure.sport.bowls': 'Bowls Facility',
  'commercial.leisure.sport.centre': 'Activity / Leisure / Sports Centre',
  'commercial.leisure.sport.cricket': 'Cricket Facility',
  'commercial.leisure.sport.curling': 'Curling Facility',
  'commercial.leisure.sport.cycling': 'Cycling Sports Facility',
  'commercial.leisure.sport.dance': 'Dance studio',
  'commercial.leisure.sport.dogracing': 'Greyhound Racing Facility',
  'commercial.leisure.sport.equestrian': 'Equestrian Sports Facility',
  'commercial.leisure.sport.firing': 'Civilian Firing Facility',
  'commercial.leisure.sport.fishing': 'Fishing / Angling Facility',
  'commercial.leisure.sport.football': 'Football Facility',
  'commercial.leisure.sport.gliding': 'Gliding Facility',
  'commercial.leisure.sport.golf': 'Golf Facility',
  'commercial.leisure.sport.hockey': 'Hockey Facility',
  'commercial.leisure.sport.horseracing': 'Horse Racing Facility',
  'commercial.leisure.sport.model': 'Model Sports Facility',
  'commercial.leisure.sport.motor': 'Motor Sports Facility',
  'commercial.leisure.sport.playingField': 'Playing Field',
  'commercial.leisure.sport.racquet': 'Racquet Sports Facility',
  'commercial.leisure.sport.recreationGround': 'Recreation Ground',
  'commercial.leisure.sport.rugby': 'Rugby Facility',
  'commercial.leisure.sport.shinty': 'Shinty Facility',
  'commercial.leisure.sport.skateboarding': 'Skateboarding Facility',
  'commercial.leisure.sport.swimming': 'Diving / Swimming Facility',
  'commercial.leisure.sport.tennis': 'Public Tennis Court',
  'commercial.leisure.sport.tenpin': 'Tenpin Bowling Facility',
  'commercial.leisure.sport.water': 'Water Sports Facility',
  'commercial.leisure.sport.wildlife': 'Wildlife Sports Facility',
  'commercial.leisure.sport.winter': 'Winter Sports Facility',
  'commercial.medical': 'Medical',
  'commercial.medical.GP': 'General Practice Surgery / Clinic',
  'commercial.medical.assessment': 'Assessment / Development Services',
  'commercial.medical.care': 'Medical care',
  'commercial.medical.careHome': 'Care home/Hospice',
  'commercial.medical.dentist': 'Dentist',
  'commercial.medical.healthCentre': 'Health Centre',
  'commercial.medical.healthServices': 'Health Care Services',
  'commercial.medical.hospital': 'Hospital',
  'commercial.medical.lab': 'Medical / Testing / Research Laboratory',
  'commercial.medical.professional': 'Professional Medical Service',
  'commercial.office': 'Office',
  'commercial.office.broadcasting': 'Broadcasting (TV / Radio)',
  'commercial.office.workspace': 'Office / Work Studio',
  'commercial.office.workspace.embassy':
    'Embassy /, High Commission / Consulate',
  'commercial.office.workspace.film': 'Film Studio',
  'commercial.office.workspace.gov.local': 'Local Government Service',
  'commercial.office.workspace.gov.national': 'Central Government Service',
  'commercial.retail': 'Retail',
  'commercial.retail.beauty':
    'Barber / Hairdresser / Beauty Salon / Tattoo Parlour',
  'commercial.retail.bettingOffice': 'Betting Office',
  'commercial.retail.drinking': 'Public House / Bar / Nightclub',
  'commercial.retail.dryCleaner': 'Dry cleaner',
  'commercial.retail.financial': 'Bank / Financial Service',
  'commercial.retail.fuel': 'Petrol Filling Station',
  'commercial.retail.laundrette': 'Laundrette',
  'commercial.retail.licensedPremises': 'Other Licensed Premise / Vendor',
  'commercial.retail.localShop': 'Local shop',
  'commercial.retail.market': 'Market (Indoor / Outdoor)',
  'commercial.retail.market.fish': 'Fish Market',
  'commercial.retail.market.fruit': 'Fruit / Vegetable Market',
  'commercial.retail.market.livestock': 'Livestock Market',
  'commercial.retail.payDayLoanShop': 'Pay day loan shop',
  'commercial.retail.post': 'Post Office',
  'commercial.retail.restaurant': 'Restaurant / Cafeteria',
  'commercial.retail.services': 'Retail Service Agent',
  'commercial.retail.shop': 'Shop',
  'commercial.retail.shop.gardenCentre': 'Garden Centre',
  'commercial.retail.showroom': 'Showroom',
  'commercial.retail.takeaway': 'Fast Food Outlet / Takeaway (Hot / Cold)',
  'commercial.retail.visitorInformation': 'Visitor Information',
  'commercial.services.audioStudio': 'Audio recording studio',
  'commercial.services.childminding': 'Childminding',
  'commercial.services.photographicStudio': 'Photographic studio',
  'commercial.storage': 'Warehouse / Store / Storage Depot',
  'commercial.storage.crops': 'Crop Handling / Storage',
  'commercial.storage.distribution': 'Wholesale Distribution',
  'commercial.storage.distribution.solidFuel': 'Solid Fuel Distribution',
  'commercial.storage.distribution.timber': 'Timber Distribution',
  'commercial.storage.hydrocarbon': 'Hydrocarbon storage',
  'commercial.storage.land': 'Storage Land',
  'commercial.storage.land.general': 'General Storage Land',
  'commercial.storage.retail': 'Retail Warehouse',
  'commercial.storage.solidFuel': 'Solid Fuel Storage',
  'commercial.storage.timber': 'Timber Storage',
  'commercial.storage.transport': 'Vehicle Storage',
  'commercial.storage.transport.boat': 'Boat Storage',
  'commercial.storage.transport.bus': 'Bus / Coach Depot',
  'commercial.transport': 'Transport',
  'commercial.transport.air':
    'Airfield / Airstrip / Airport / Air Transport Infrastructure Facility',
  'commercial.transport.air.airfield': 'Airfield',
  'commercial.transport.air.airport': 'Airport',
  'commercial.transport.air.helicopterStation': 'Helicopter Station',
  'commercial.transport.air.heliport': 'Heliport / Helipad',
  'commercial.transport.air.infrastructure':
    'Air Transport Infrastructure Services',
  'commercial.transport.air.passengerTerminal': 'Air Passenger Terminal',
  'commercial.transport.freight': 'Goods Freight Handling / Terminal',
  'commercial.transport.freight.air': 'Air Freight Terminal',
  'commercial.transport.freight.container': 'Container Freight',
  'commercial.transport.freight.rail': 'Rail Freight Transport',
  'commercial.transport.freight.road': 'Road Freight Transport',
  'commercial.transport.infrastructure': 'Transport Related Infrastructure',
  'commercial.transport.rail.monorail': 'Monorail',
  'commercial.transport.rail.railAsset': 'Railway Asset',
  'commercial.transport.rail.terminal': 'Train station',
  'commercial.transport.rail.track': 'Transport Track / Railway',
  'commercial.transport.road.bus': 'Bus Shelter',
  'commercial.transport.road.infrastructure.weighing':
    'Weighbridge / Load Gauge',
  'commercial.transport.road.overnightLorryPark': 'Overnight Lorry Park',
  'commercial.transport.road.parking':
    'Car / Coach / Commercial Vehicle / Taxi Parking / Park And Ride Site',
  'commercial.transport.road.parking.car': 'Public Car Parking',
  'commercial.transport.road.parking.coach': 'Public Coach Parking',
  'commercial.transport.road.parking.commercialVehicle':
    'Public Commercial Vehicle Parking',
  'commercial.transport.road.parking.parkAndRide': 'Public Park And Ride',
  'commercial.transport.road.terminal.bus': 'Bus station',
  'commercial.transport.terminal': 'Station / Interchange / Terminal / Halt',
  'commercial.transport.track.cable': 'Chair Lift / Cable Car / Ski Tow',
  'commercial.transport.water.dock':
    'Harbour / Port / Dock / Dockyard / Slipway / Landing Stage / Pier / Jetty / Pontoon / Terminal / Berthing / Quay',
  'commercial.transport.water.dock.ferry.passengers':
    'Passenger Ferry Terminal',
  'commercial.transport.water.dock.ferry.vehicles': 'Vehicular Ferry Terminal',
  'commercial.transport.water.dock.generalBerth':
    'Non-Tanker Nautical Berthing',
  'commercial.transport.water.dock.passenger': 'Ship Passenger Terminal',
  'commercial.transport.water.dock.refuelling': 'Nautical Refuelling Facility',
  'commercial.transport.water.dock.slipway': 'Slipway',
  'commercial.transport.water.dock.tankerBerth': 'Tanker Berthing',
  'commercial.transport.water.infrastructure.aqueduct': 'Aqueduct',
  'commercial.transport.water.infrastructure.lock': 'Lock',
  'commercial.transport.water.infrastructure.weir': 'Weir',
  'commercial.transport.water.marina': 'Marina',
  'commercial.transport.water.mooring': 'Mooring',
  'commercial.utility': 'Utility',
  'commercial.utility.CCTV': 'CCTV',
  'commercial.utility.atm': 'Automated Teller Machine (ATM)',
  'commercial.utility.dam': 'Dam',
  'commercial.utility.electricity': 'Power Station / Energy Production',
  'commercial.utility.electricity.distribution':
    'Electricity Distribution Facility',
  'commercial.utility.electricity.production':
    'Electricity Production Facility',
  'commercial.utility.electricity.solarFarm': 'Solar farms',
  'commercial.utility.electricity.substation': 'Electricity Sub-Station',
  'commercial.utility.electricity.windFarm': 'Wind Farm',
  'commercial.utility.electricity.windTurbine': 'Wind Turbine',
  'commercial.utility.landfill': 'Landfill',
  'commercial.utility.oilGas': 'Gas / Oil Storage / Distribution',
  'commercial.utility.oilGas.gasGovernor': 'Gas Governor',
  'commercial.utility.oilGas.gasHolder': 'Gas Holder',
  'commercial.utility.oilGas.oilTerminal': 'Oil Terminal',
  'commercial.utility.other': 'Other Utility Use',
  'commercial.utility.other.cableTerminal': 'Cable Terminal Station',
  'commercial.utility.other.observatory': 'Observatory',
  'commercial.utility.other.radar': 'Radar Station',
  'commercial.utility.other.satelliteEarth': 'Satellite Earth Station',
  'commercial.utility.publicPhone.box': 'Telephone Box',
  'commercial.utility.publicPhone.other': 'Other Public Telephones',
  'commercial.utility.telecoms': 'Telecommunication',
  'commercial.utility.telecoms.exchange': 'Telephone Exchange',
  'commercial.utility.telecoms.mast': 'Telecommunications Mast',
  'commercial.utility.wasteManagement': 'Waste Management',
  'commercial.utility.water': 'Pump House / Pumping Station / Water Tower',
  'commercial.utility.water.floodControl': 'Flood control infrastructure',
  'commercial.utility.water.pump.control': 'Water Controlling / Pumping',
  'commercial.utility.water.pump.distribution': 'Water Distribution / Pumping',
  'commercial.utility.water.qualityMonitoring': 'Water Quality Monitoring',
  'commercial.utility.water.storage': 'Water Storage',
  'commercial.utility.water.treatment':
    'Water / Waste Water / Sewage Treatment Works',
  'commercial.utility.water.waste': 'Waste Water Distribution / Pumping',
  'commercial.utility.water.wasteTreatment': 'Waste Water Treatment',
  'commercial.utility.water.waterTreatment': 'Water Treatment',
  dualUse: 'Dual Use',
  land: 'Land',
  'land.allotment': 'Allotment',
  'land.amenity': 'Amenity - Open areas not attracting visitors',
  'land.amenity.natural': 'Verge / Central Reservation',
  'land.amenity.natural.centralReservation': 'Natural Central Reservation',
  'land.amenity.natural.verge': 'Natural Verge',
  'land.amenity.roundabout': 'Landscaped Roundabout',
  'land.amenity.surface': 'Maintained Amenity Land',
  'land.amenity.surface.centralReservation': 'Made Central Reservation',
  'land.amenity.surface.pavement': 'Pavement',
  'land.aviation': 'Aviation operational land',
  'land.burial': 'Burial Ground',
  'land.burial.historic': 'Historic / Disused Cemetery / Graveyard',
  'land.development': 'Development',
  'land.development.construction': 'Development Site',
  'land.development.construction.commercial': 'Commercial Construction Site',
  'land.development.construction.community': 'Community Construction Site',
  'land.development.construction.residential': 'Residential Construction Site',
  'land.development.construction.transport': 'Transport Construction Site',
  'land.forest': 'Forestry',
  'land.forest.arboretum': 'Arboretum',
  'land.forest.woods': 'Woodland',
  'land.highways': 'Land within boundaries of a road',
  'land.industrial': 'Industrial land',
  'land.open': 'Open Space',
  'land.open.moor': 'Heath / Moorland',
  'land.park': 'Park',
  'land.park.natureReserve': 'Public Open Space / Nature Reserve',
  'land.park.play': 'Playground',
  'land.park.play.paddlingPool': 'Paddling Pool',
  'land.park.play.playground': 'Play Area',
  'land.park.private': 'Private Park / Garden',
  'land.park.public': 'Public Park / Garden',
  'land.smallholding': 'Smallholding',
  'land.unused': 'Unused Land',
  'land.unused.vacant': 'Vacant land / derelict building',
  'land.water': 'Water',
  'land.water.pond': 'Named Pond',
  'land.water.pond.decoy': 'Decoy Pond',
  'land.water.pond.dew': 'Dew Pond',
  'land.water.pond.static': 'Static Water',
  'land.water.reservoir': 'Lake / Reservoir',
  'land.water.reservoir.buried': 'Buried Reservoir',
  'land.water.reservoir.pond': 'Balancing Pond',
  'land.water.way': 'Waterway',
  'land.water.way.drain': 'Drain',
  'land.water.way.leatsRaces': 'Leats / Races',
  military: 'Military',
  'military.airForce': 'Air Force',
  'military.airForce.range': 'Air Force Military Range',
  'military.airForce.site': 'Air Force Site',
  'military.airForce.storage': 'Air Force Military Storage',
  'military.airForce.training': 'Air Force Military Training',
  'military.army': 'Army',
  'military.army.range': 'Army Military Range',
  'military.army.site': 'Army Site',
  'military.army.storage': 'Army Military Storage',
  'military.army.training': 'Army Military Training',
  'military.barracks': 'Military Barracks',
  'military.building': 'Ancillary Building',
  'military.building.target': 'Military Target',
  'military.defenceEstates': 'Defence Estates',
  'military.navy': 'Navy',
  'military.navy.range': 'Naval Military Range',
  'military.navy.site': 'Naval Site',
  'military.navy.storage': 'Naval Military Storage',
  'military.navy.training': 'Naval Military Training',
  mixedUse: 'Mixed use (within single planning unit)',
  object: 'Object of Interest',
  'object.archaeological': 'Archaeological Dig Site',
  'object.monument': 'Monument',
  'object.monument.memorial': 'Memorial / Market Cross',
  'object.monument.other': 'Other Structure',
  'object.monument.other.art': 'Permanent Art Display / Sculpture',
  'object.monument.other.boundaryStone': 'Boundary Stone',
  'object.monument.other.waterFeature': 'Cascade / Fountain',
  'object.monument.other.windmill': 'Windmill (Inactive)',
  'object.monument.ruin': 'Castle / Historic Ruin',
  'object.monument.statue': 'Statue',
  'object.monument.vertical': 'Obelisk / Milestone / Standing Stone',
  'object.monument.vertical.obelisk': 'Obelisk',
  'object.monument.vertical.standingStone': 'Standing Stone',
  'object.religious': 'Place Of Worship',
  'object.religious.building': 'Religious building',
  'object.religious.building.abbey': 'Abbey',
  'object.religious.building.cathedral': 'Cathedral',
  'object.religious.building.chapel': 'Chapel',
  'object.religious.building.church': 'Church',
  'object.religious.building.gurdwara': 'Gurdwara',
  'object.religious.building.kingdomHall': 'Kingdom Hall',
  'object.religious.building.lychGate': 'Lych Gate',
  'object.religious.building.minster': 'Minster',
  'object.religious.building.mosque': 'Mosque',
  'object.religious.building.stupa': 'Stupa',
  'object.religious.building.synagogue': 'Synagogue',
  'object.religious.building.temple': 'Temple',
  'object.statelyHome': 'Stately Home',
  'object.underground': 'Underground Feature',
  'object.underground.cave': 'Cave',
  'object.underground.hole': 'Pothole / Natural Hole',
  'object.underground.other': 'Other Underground Feature',
  'object.underground.other.cellar': 'Cellar',
  'object.underground.other.extraction': 'Disused Mine',
  'object.underground.other.extraction.mine': 'Mineral Mining / Inactive',
  'object.underground.other.extraction.oilGas':
    'Oil And / Gas Extraction/ Inactive',
  'object.underground.other.extraction.quarry':
    'Mineral Quarrying And / Open Extraction / Inactive',
  'object.underground.other.water': 'Well / Spring',
  'object.underground.other.water.spring': 'Spring',
  'object.underground.other.water.well': 'Well',
  other: 'Other (Ordnance Survey only)',
  'other.agriculture': 'Agricultural Support Objects',
  'other.agriculture.currick': 'Currick',
  'other.agriculture.fishPen': 'Fish Ladder / Lock / Pen / Trap',
  'other.agriculture.livestockPen': 'Livestock Pen / Dip',
  'other.agriculture.slurry': 'Slurry Bed / Pit',
  'other.ancillary': 'Ancillary Building',
  'other.ancillary.aviary': 'Aviary / Dovecot / Cage',
  'other.ancillary.bandstand': 'Bandstand',
  'other.ancillary.pavilion': 'Pavilion / Changing Room',
  'other.ancillary.sportsViewing': 'Sports Viewing Structure',
  'other.coastal': 'Coastal Protection / Flood Prevention',
  'other.coastal.floodGate': 'Flood Gate / Flood Sluice Gate / Flood Valve',
  'other.coastal.groyne': 'Groyne',
  'other.coastal.ripRap': 'Rip-Rap',
  'other.coastal.wall': 'Boulder Wall / Sea Wall',
  'other.emergency': 'Emergency Support',
  'other.emergency.fire':
    'Fire Alarm Structure / Fire Observation Tower / Fire Beater Facility',
  'other.emergency.firstAid': 'Beach Office / First Aid Facility',
  'other.emergency.floatAids':
    'LIfe / Belt / Buoy / Float / Jacket / Safety Rope',
  'other.emergency.telephone': 'Emergency Telephone (Non Motorway)',
  'other.emergency.warning':
    'Emergency Equipment Point / Emergency Siren / Warning Flag',
  'other.historic': 'Historical Site / Object',
  'other.historic.structure': 'Historic Structure / Object',
  'other.industrial': 'Industrial Support',
  'other.industrial.aditIncline': 'Adit / Incline / Level',
  'other.industrial.caissonDock': 'Caisson / Dry Dock / Grid',
  'other.industrial.channel': 'Channel / Conveyor / Conduit / Pipe',
  'other.industrial.chimney': 'Chimney / Flue',
  'other.industrial.coolingTower': 'Cooling Tower',
  'other.industrial.crane': 'Crane / Hoist / Winch / Material Elevator',
  'other.industrial.discharge':
    'Grab / Skip / Other Industrial Waste Machinery / Discharging',
  'other.industrial.flareStack': 'Flare Stack',
  'other.industrial.kiln': 'Kiln / Oven / Smelter',
  'other.industrial.manholeShaft': 'Manhole / Shaft',
  'other.industrial.overflowSluiceValve':
    'Industrial Overflow / Sluice / Valve / Valve Housing',
  'other.industrial.pylon.electricity': 'Electricity Distribution Pole / Pylon',
  'other.industrial.pylon.telecom': 'Telephone Pole / Post',
  'other.industrial.siloTank': 'Hopper / Silo / Cistern / Tank',
  'other.industrial.solarPanel': 'Solar Panel / Waterwheel',
  'other.information': 'Information',
  'other.information.advertising': 'Advertising Hoarding',
  'other.information.touristSign': 'Tourist Information Signage',
  'other.information.trafficSign': 'Traffic Information Signage',
  'other.leisure': 'Sport / Leisure Support',
  'other.leisure.gallop': 'Gallop / Ride',
  'other.leisure.hide': 'Butt / Hide',
  'other.leisure.modelRailway': 'Miniature Railway',
  'other.mail': 'Royal Mail Infrastructure',
  'other.mail.POBox': 'PO Box',
  'other.mail.additionalAddressee': 'Additional Mail / Packet Addressee',
  'other.mail.deliveryBox': 'Postal Delivery Box / Pouch',
  'other.mail.postBox': 'Postal Box',
  'other.natural': 'Significant Natural Object',
  'other.natural.hole': 'Natural Hole (Blow / Shake / Swallow)',
  'other.natural.rock': 'Boundary / Significant Rock / Boulder',
  'other.natural.tree': 'Boundary / Significant / Historic Tree / Pollard',
  'other.navigation': 'Aid To Navigation',
  'other.navigation.air': 'Aid To Aeronautical Navigation',
  'other.navigation.air.beacon': 'Aeronautical Navigation Beacon / Light',
  'other.navigation.air.landingLight': 'Landing Light',
  'other.navigation.air.signalSquare': 'Signal Square',
  'other.navigation.air.windSock': 'Wind Sock / Wind Tee',
  'other.navigation.guidePost': 'Guide Post',
  'other.navigation.nautical': 'Aid To Nautical Navigation',
  'other.navigation.nautical.beacon': 'Nautical Navigation Beacon / Light',
  'other.navigation.nautical.daymark': 'Daymark',
  'other.navigation.nautical.fogHorn': 'Fog Horn Warning',
  'other.navigation.road': 'Aid To Road Navigation',
  'other.ornamental': 'Ornamental / Cultural Object',
  'other.ornamental.maze': 'Maze',
  'other.ornamental.object': 'Simple Ornamental Object',
  'other.ornamental.tomb': 'Mausoleum / Tomb / Grave',
  'other.scientific': 'Scientific / Observation Support',
  'other.scientific.astronomy':
    'Telescope / Observation Infrastructure / Astronomy',
  'other.scientific.meteo': 'Meteorological Station / Equipment',
  'other.scientific.radarSatellite': 'Radar / Satellite Infrastructure',
  'other.streetFurniture': 'Street Furniture',
  'other.transport': 'Transport Support',
  'other.transport.bridge': 'Footbridge / Walkway',
  'other.transport.cattleGridFord': 'Cattle Grid / Ford',
  'other.transport.customs': 'Customs Inspection Facility',
  'other.transport.goodsTramway': 'Goods Tramway',
  'other.transport.layby': 'Lay-By',
  'other.transport.mailPickUp': 'Mail Pick Up',
  'other.transport.post':
    'Pole / Post / Bollard (Restricting Vehicular Access)',
  'other.transport.rail.buffer': 'Railway Buffer',
  'other.transport.rail.crossing.pedestrian': 'Railway Pedestrian Crossing',
  'other.transport.rail.crossing.vehicles': 'Level Crossing',
  'other.transport.rail.drag': 'Rail Drag',
  'other.transport.rail.infrastructure': 'Rail Infrastructure Services',
  'other.transport.rail.lighting': 'Railway Lighting',
  'other.transport.rail.marker.km': 'Rail Kilometre Distance Marker',
  'other.transport.rail.market.mile': 'Rail Mile Distance Marker',
  'other.transport.rail.signals': 'Rail Signalling',
  'other.transport.rail.traverse': 'Railway Traverse',
  'other.transport.rail.turntable': 'Railway Turntable',
  'other.transport.rail.weighbridge': 'Rail Weighbridge',
  'other.transport.road.drag': 'Road Drag',
  'other.transport.road.infrastructure': 'Road Infrastructure Services',
  'other.transport.road.marker.mile': 'Road Mile Distance Marker',
  'other.transport.road.market.km': 'Road Kilometre Distance Marker',
  'other.transport.road.turntable': 'Road Turntable',
  'other.transport.road.vehicleDip': 'Vehicle Dip',
  'other.transport.stepsLiftEscalator': 'Elevator / Escalator / Steps',
  'other.transport.subway': 'Subway / Underpass',
  'other.unsupported': 'Unsupported Site',
  'other.unsupported.cycleParking': 'Cycle Parking Facility',
  'other.unsupported.picnic': 'Picnic / Barbeque Site',
  'other.unsupported.shelter': 'Shelter (Not Including Bus Shelter)',
  'other.unsupported.travellingPersons': 'Travelling Persons Site',
  parent: 'Parent Shell',
  'parent.property': 'Property Shell',
  'parent.street': 'Street Record',
  residential: 'Residential',
  'residential.ancillary': 'Ancillary Building',
  'residential.boat': 'House Boat',
  'residential.carParkingSpace': 'Car Park Space',
  'residential.carParkingSpace.allocated': 'Allocated Parking',
  'residential.caravan': 'Caravan',
  'residential.childrensHome': 'Children’s home',
  'residential.extraCareHousing': 'Extra care housing',
  'residential.flat': 'Flat',
  'residential.garage': 'Garage',
  'residential.holiday': 'Privately Owned Holiday Caravan / Chalet',
  'residential.HMO': 'House In Multiple Occupation',
  'residential.HMO.bedsit':
    'HMO Bedsit / Other Non Self Contained Accommodation',
  'residential.HMO.parent': 'HMO Parent',
  'residential.HMO.undivided': 'HMO Not Further Divided',
  'residential.house': 'House',
  'residential.house.detached': 'Detached',
  'residential.house.semiDetached': 'Semi-detached',
  'residential.house.terrace': 'Terrace',
  'residential.institution': 'Residential Institution',
  'residential.institution.care': 'Care / Nursing Home',
  'residential.institution.communal': 'Communal Residence',
  'residential.institution.education': 'Residential Education',
  'residential.institution.noncommercial': 'Non-Commercial Lodgings',
  'residential.institution.religious': 'Religious Community',
  'residential.mobileHome': 'Mobile home',
  'residential.multiple': 'Multiple residential units',
  'residential.parkHome': 'Park home',
  'residential.serviced': 'Serviced accommodation',
  'residential.shelteredAccommodation': 'Sheltered Accommodation',
  unclassified: 'Unclassified',
  'unclassified.awaitingclassification': 'Awaiting Classification',
  'unclassified.pendingInvestigation': 'Pending Internal Investigation',
};

type PropertyTypeKeys = keyof typeof PropertyTypes;

type GenericPropertyType<TKey extends PropertyTypeKeys> = {
  value: TKey;
  description: (typeof PropertyTypes)[TKey];
};

type PropertyTypeMap = {
  [K in PropertyTypeKeys]: GenericPropertyType<K>;
};

/**
 * @id #PropertyType
 * @description Property types derived from Basic Land and Property Unit (BLPU) classification codes
 */
export type PropertyType = PropertyTypeMap[keyof PropertyTypeMap];
