import {BaseMetadata} from '../../shared/Metadata';
import {DateTime} from '../../shared/utils';
import {PrototypePlanXMetadata} from '../prototypeApplication/Metadata';

type PostSubmissionMetadataBase = {
  /**
   * This is the date the schema for this application was generated by the API/file system.
   *
   * Most of the time this value will be the current dateTime.
   *
   * However, if the schema is being used to represent historic or legacy applications as static
   * files in a directory then this will be the date the export was done and the file was generated.
   *
   */
  generatedAt: DateTime;
};

type PostSubmissionBaseMetadata = BaseMetadata & PostSubmissionMetadataBase;
type PostSubmissionPrototypePlanXMetadata = PrototypePlanXMetadata &
  PostSubmissionMetadataBase;

export type PostSubmissionMetadata =
  | PostSubmissionBaseMetadata
  | PostSubmissionPrototypePlanXMetadata;
