/**
 * Values of `file.type`
 */
export const FileTypes = {
  'applicant.disability.evidence':
    'Evidence for application fee exemption - disability',
  'property.drawing.elevation': 'Elevations - existing',
  'property.drawing.floorPlan': 'Floor plan - existing',
  'property.drawing.roofPlan': 'Roof plan - existing',
  'property.drawing.section': 'Sections - existing',
  'property.drawing.sitePlan': 'Site plan - existing',
  'property.drawing.usePlan': 'Use plan - existing',
  'property.photograph': 'Photographs - existing',
  'proposal.drawing.elevation': 'Elevations - proposed',
  'proposal.drawing.floorPlan': 'Floor plan - proposed',
  'proposal.drawing.locationPlan': 'Location plan',
  'proposal.drawing.other': 'Other - drawing',
  'proposal.drawing.roofPlan': 'Roof plan - proposed',
  'proposal.drawing.section': 'Sections - proposed',
  'proposal.drawing.sketchPlan': 'Sketch plan',
  'proposal.drawing.sitePlan': 'Site plan - proposed',
  'proposal.drawing.unitPlan': 'Unit plan - proposed',
  'proposal.drawing.usePlan': 'Use plan - proposed',
  'proposal.document.arboriculturistReport': 'Arboriculturist report',
  'proposal.document.bankStatement': 'Bank statement',
  'proposal.document.buildingControl.certificate':
    'Building control certificate',
  'proposal.document.construction.invoice': 'Construction invoice',
  'proposal.document.contamination': 'Contamination report',
  'proposal.document.councilTaxBill': 'Council tax bill',
  'proposal.document.declaration': 'Statuatory declaration',
  'proposal.document.designAndAccess': 'Design and Access Statement',
  'proposal.document.fireSafety': 'Fire safety report',
  'proposal.document.floodRisk': 'Flood risk assessment',
  'proposal.document.heritageStatement': 'Heritage Statement',
  'proposal.document.noise': 'Noise assessment',
  'proposal.document.other': 'Other - document',
  'proposal.document.other.evidence': 'Other - correspondence',
  'proposal.document.subsidenceReport': 'Subsidence report',
  'proposal.document.sunAndDaylight': 'Sunlight and daylight report',
  'proposal.document.technicalEvidence': 'Technical evidence',
  'proposal.document.tenancyAgreement': 'Tenancy agreement',
  'proposal.document.tenancyInvoice': 'Tenancy invoice',
  'proposal.document.transport': 'Transport assessment',
  'proposal.document.treeConditionReport': 'Tree condition report',
  'proposal.document.utility.bill': 'Utility bill',
  'proposal.photograph': 'Photographs - proposed',
  'proposal.photograph.evidence': 'Photographs - evidence',
  'proposal.visualisation': 'Visualisations',
};
