/**
 * Values for data.property use or data.proposal.use
 */
export const LandUses = {
  agriculture: 'Agriculture',
  business: 'Offices or R&D lab',
  'business.lightIndustry': 'Light industry',
  'business.offices': 'Offices',
  'business.RandD': 'R&D lab',
  'changeOfUse.commercial.advert': 'Display an advert',
  'changeOfUse.commercial.leisure.holiday.camping': 'Campsite or caravan park',
  'changeOfUse.commercial.leisure.sport': 'Sports',
  'changeOfUse.commercial.leisure.sport.clayPigeon': 'Clay pigeon shooting',
  'changeOfUse.commercial.leisure.sport.equestrian': 'Keeping horses',
  'changeOfUse.commercial.leisure.sport.firearms': 'Firearms',
  'changeOfUse.commercial.leisure.sport.motorRacing': 'Motor racing',
  'changeOfUse.commercial.leisure.sport.running': 'Running race',
  'changeOfUse.commercial.leisure.sport.warGame': 'War game',
  'changeOfUse.commercial.storageLand': 'Storage land',
  'changeOfUse.commercial.temporary': 'Temporary market',
  'changeOfUse.land.agriculture': 'Agriculture',
  'changeOfUse.land.allotment': 'Allotment',
  'changeOfUse.land.natural': 'Natural landscape',
  'changeOfUse.land.unused.vacant': 'Vacant land',
  'changeOfUse.residential.garden': 'Garden of a home',
  'commercial.advert': 'Display an advert',
  'commercial.leisure.holiday.camping': 'Campsite or caravan park',
  'commercial.leisure.sport': 'Sports',
  'commercial.leisure.sport.clayPigeon': 'Clay pigeon shooting',
  'commercial.leisure.sport.equestrian': 'Keeping horses',
  'commercial.leisure.sport.firearms': 'Firearms',
  'commercial.leisure.sport.motorRacing': 'Motor racing',
  'commercial.leisure.sport.running': 'Running race',
  'commercial.leisure.sport.warGame': 'War game',
  'commercial.storageLand': 'Storage land',
  'commercial.temporary': 'Temporary market',
  guest: 'Hotel or guesthouse',
  'guest.guesthouse': 'Guesthouse',
  'guest.hostel': 'Hostel',
  'guest.hotel': 'Hotel',
  industrial: 'Industrial',
  'industrial.alkalis': 'Alkalis',
  'industrial.chemicals': 'Chemicals',
  'industrial.heavy': 'Heavy industry',
  'industrial.metals': 'Metals',
  'industrial.skins': 'Skins',
  'industrial.storage': 'Industrial storage',
  'industrial.waste': 'Industrial waste',
  institutions: 'Institution',
  'institutions.court': 'Court house',
  'institutions.education': 'Educational institution',
  'institutions.education.school': 'School',
  'institutions.exhibition': 'Exhibition',
  'institutions.gallery': 'Gallery',
  'institutions.health': 'Health institution',
  'institutions.library': 'Library',
  'institutions.museum': 'Museum',
  'institutions.nursery': 'Nursery',
  'institutions.religion': 'Religious institution',
  'institutions.school': 'School',
  land: 'Land',
  'land.agriculture': 'Agriculture',
  'land.allotment': 'Allotment',
  'land.natural': 'Natural landscape',
  'land.unused.vacant': 'Vacant land',
  leisure: 'Leisure',
  'leisure.amusements': 'Amusement park',
  'leisure.betting': 'Betting shop',
  'leisure.bingo': 'Bingo hall',
  'leisure.casino': 'Casino',
  'leisure.cinema': 'Cinema',
  'leisure.community': 'Community space',
  'leisure.danceHall': 'Dance hall',
  'leisure.funfair': 'Fun fair',
  'leisure.gym': 'Gymnasium',
  'leisure.music': 'Music venue',
  'leisure.nightclub': 'Night club',
  'leisure.skating': 'Skating rink',
  'leisure.sport.indoor': 'Indoor sports',
  'leisure.sport.outdoor': 'Outdoor sports',
  'leisure.swimming': 'Swimming pool',
  'leisure.theatre': 'Theatre',
  residential: 'Residential',
  'residential.careHome': 'Care home',
  'residential.education.college': 'College dormitories',
  'residential.education.school': 'School dormitories',
  'residential.education.training': 'Educational training dormitories',
  'residential.garden': 'Garden of a home',
  'residential.HMO': 'House with Multiple Occupants (HMO)',
  'residential.HMO.large': 'Large House with Multiple Occupants (HMO)',
  'residential.HMO.small': 'Small House with Multiple Occupants (HMO)',
  'residential.home': 'Residential home',
  'residential.home.care': 'Care home',
  'residential.home.largeHouseholds': 'Large household home',
  'residential.home.singleFamily': 'Single family home',
  'residential.hospital': 'Hospital',
  'residential.secure': 'Secure residential',
  retail: 'Retail',
  'retail.art': 'Art studio',
  'retail.carShowroom': 'Vehicle showroom',
  'retail.cashAndCarry': 'Cash and carry',
  'retail.deli': 'Deli',
  'retail.dryCleaner': 'Dry cleaner',
  'retail.funeral': 'Funeral parlour',
  'retail.hairdresser': 'Hairdresser',
  'retail.hire': 'Hire shop',
  'retail.internet': 'Internet cafe',
  'retail.laundrette': 'Laundrette',
  'retail.petrolStation': 'Petrol station',
  'retail.postOffice': 'Post office',
  'retail.restaurants': 'Restaurants',
  'retail.restaurants.drinking': 'Pub',
  'retail.services': 'Financial or professional service',
  'retail.services.accounting': 'Accountancy service',
  'retail.services.bank': 'Bank',
  'retail.services.buildingSociety': 'Building society',
  'retail.services.carHire': 'Vehicle hire location',
  'retail.services.employmentAgency': 'Employment agency',
  'retail.services.estateAgent': 'Estate agent',
  'retail.services.legal': 'Legal service',
  'retail.services.payDayLoans': 'Pay day loan shop',
  'retail.services.taxi': 'Taxi office',
  'retail.shop': 'Retail shop',
  'retail.shop.food': 'Food or grocery shop (including off licenses)',
  'retail.shop.local': 'Local goods shop',
  'retail.shop.other': 'Another type of shop',
  'retail.takeaway': 'Hot food takeaway, bakery or delicatessen',
  'retail.travel': 'Travel agent',
  'retail.warehouse': 'Retail warehouse',
  vacant: 'Vacant land',
};
