/**
 * Values for data.property use or data.proposal.use
 */
export const LandUses = {
  advert: 'Display an advert',
  agriculture: 'Agriculture',
  'agriculture.natural': 'Natural landscape',
  allotment: 'Allotment',
  business: 'Offices or R&D lab',
  'business.lightIndustry': 'Light industry',
  'business.offices': 'Offices',
  'business.RandD': 'R&D lab',
  guest: 'Hotel or guesthouse',
  'guest.guesthouse': 'Guesthouse',
  'guest.hostel': 'Hostel',
  'guest.hotel': 'Hotel',
  industrial: 'Industrial',
  'industrial.alkalis': 'Alkalis',
  'industrial.chemicals': 'Chemicals',
  'industrial.heavy': 'Heavy industry',
  'industrial.metals': 'Metals',
  'industrial.skins': 'Skins',
  'industrial.storage': 'Industrial storage',
  'industrial.waste': 'Industrial waste',
  institutions: 'Institution',
  'institutions.court': 'Court house',
  'institutions.education': 'Educational institution',
  'institutions.education.nursery': 'Registered nursery',
  'institutions.education.school': 'School',
  'institutions.exhibition': 'Exhibition hall',
  'institutions.gallery': 'Art gallery',
  'institutions.health': 'Health centre or GP',
  'institutions.library': 'Public library',
  'institutions.museum': 'Museum',
  'institutions.nursery': 'Nursery or creche',
  'institutions.other': 'Other institution',
  'institutions.religion': 'Religious building',
  'institutions.school': 'School',
  leisure: 'Leisure',
  'leisure.amusements': 'Amusement arcade',
  'leisure.betting': 'Betting shop',
  'leisure.bingo': 'Bingo hall',
  'leisure.casino': 'Casino',
  'leisure.cinema': 'Cinema',
  'leisure.community': 'Community hall',
  'leisure.danceHall': 'Dance hall',
  'leisure.funfair': 'Funfair',
  'leisure.gym': 'Gymnasium',
  'leisure.holiday.camping': 'Campsite or caravan park',
  'leisure.music': 'Music venue',
  'leisure.nightclub': 'Night club',
  'leisure.skating': 'Skating rink',
  'leisure.sport': 'Sports',
  'leisure.sport.clayPigeon': 'Clay pigeon shooting',
  'leisure.sport.equestrian': 'Keeping horses',
  'leisure.sport.equestrian.breeding': 'Breeding studs',
  'leisure.sport.equestrian.horceRacing': 'Horce racing',
  'leisure.sport.equestrian.personal': 'Keeping horses for personal enjoyment',
  'leisure.sport.equestrian.ridingSchool': 'Equestrian riding school',
  'leisure.sport.firearms': 'Firearms',
  'leisure.sport.indoor': 'Indoor sports facility',
  'leisure.sport.motorRacing': 'Motor racing',
  'leisure.sport.outdoor': 'Outdoor sports facility',
  'leisure.sport.running': 'Running race',
  'leisure.sport.warGame': 'War game',
  'leisure.swimming': 'Public swimming pool',
  'leisure.theatre': 'Theatre',
  residential: 'Residential',
  'residential.careHome': 'Care home',
  'residential.education.college': 'College dormitories',
  'residential.education.school': 'School dormitories',
  'residential.education.training': 'Educational training dormitories',
  'residential.garden': 'Garden of a home',
  'residential.HMO': 'Shared house (or House in Multiple Occupation)',
  'residential.HMO.large': 'Large shared house',
  'residential.HMO.small': 'Small shared house',
  'residential.home': 'Residential home or homes',
  'residential.home.care': 'Supported care home',
  'residential.home.children': "Children's home",
  'residential.home.multiple': 'Multiple homes',
  'residential.home.single': 'Single home',
  'residential.hospital': 'Hospital',
  'residential.secure': 'Secure residential',
  retail: 'Retail',
  'retail.art': 'Art studio',
  'retail.carShowroom': 'Vehicle showroom',
  'retail.cashAndCarry': 'Cash and carry',
  'retail.deli': 'Deli',
  'retail.drinking': 'Bar or pub',
  'retail.dryCleaner': 'Dry cleaner',
  'retail.funeral': 'Funeral parlour',
  'retail.hairdresser': 'Hairdresser',
  'retail.hire': 'Hire shop',
  'retail.internet': 'Internet cafe',
  'retail.laundrette': 'Laundrette',
  'retail.petrolStation': 'Petrol station',
  'retail.postOffice': 'Post office',
  'retail.restaurants': 'Restaurant or cafe',
  'retail.restaurants.drinking':
    'Drinking establishment with expanded food provision',
  'retail.services': 'Financial or professional service',
  'retail.services.accounting': 'Accountancy service',
  'retail.services.bank': 'Bank',
  'retail.services.buildingSociety': 'Building society',
  'retail.services.carHire': 'Vehicle hire location',
  'retail.services.employment': 'Employment agency',
  'retail.services.estateAgent': 'Estate agent',
  'retail.services.legal': 'Legal service',
  'retail.services.payDayLoans': 'Pay day loan shop',
  'retail.services.taxi': 'Taxi office',
  'retail.shop': 'Retail shop',
  'retail.shop.food': 'Food or grocery shop (including off licenses)',
  'retail.shop.local': 'Local goods shop',
  'retail.shop.other': 'Another type of shop',
  'retail.takeaway': 'Hot food takeaway, bakery or delicatessen',
  'retail.travel': 'Travel agent',
  'retail.warehouse': 'Retail warehouse',
  storageLand: 'Storage land',
  temporary: 'Temporary market',
  vacant: 'Vacant land',
};
