/**
 * Values of `data.proposal.projectType`
 */
export const ProjectTypes = {
  alter: 'Alter a building',
  'alter.balcony': 'Add or alter a balcony',
  'alter.bayWindow': 'Add or remove a bay window',
  'alter.bayWindow.add': 'Add a bay window',
  'alter.bayWindow.rear': 'Add a bay window to the rear of the building',
  'alter.bayWindow.remove': 'Remove a bay window',
  'alter.boundary': 'Changes to a fence, wall or gate',
  'alter.boundary.add': 'Add a new fence, wall or gate',
  'alter.boundary.add.fence': 'Add a new fence',
  'alter.boundary.add.gate': 'Add a new gate',
  'alter.boundary.add.wall': 'Add a new boundary wall',
  'alter.boundary.alter': 'Change a fence, wall or gate',
  'alter.boundary.remove': 'Remove a fence, wall, or gate',
  'alter.boundary.repair': 'Repair a fence, wall or gate',
  'alter.boundary.repair.fence': 'Repair a fence',
  'alter.boundary.repair.gate': 'Repair a gate',
  'alter.boundary.repair.wall': 'Repair a wall',
  'alter.boundary.replace': 'Replace a fence, wall or gate',
  'alter.boundary.replace.fence': 'Replace a fence',
  'alter.boundary.replace.gate': 'Replace a gate',
  'alter.boundary.replace.wall': 'Replace a wall',
  'alter.cables': 'Install underground cables',
  'alter.changeOfMaterials.boundary':
    'Change the material of a fence, wall or gate',
  'alter.changeOfMaterials.chimney': 'Change the material of chimneys',
  'alter.changeOfMaterials.externalDoors':
    'Change the material of external doors',
  'alter.changeOfMaterials.externalWalls':
    'Change the material of external walls',
  'alter.changeOfMaterials.floors': 'Change the material of floors',
  'alter.changeOfMaterials.hardstanding':
    'Change the material of vehicle access or hardstanding',
  'alter.changeOfMaterials.internalDoors':
    'Change the material of internal doors',
  'alter.changeOfMaterials.internalWalls':
    'Change the material of internal walls',
  'alter.changeOfMaterials.other': 'Change the material of something else',
  'alter.changeOfMaterials.rainwaterGoods':
    'Change the material of rainwater goods',
  'alter.changeOfMaterials.roofCovering':
    'Change the material of roof coverings',
  'alter.changeOfMaterials.windows': 'Change the material of windows',
  'alter.chimneys': 'Change chimneys',
  'alter.chimneys.add': 'Add a chimney',
  'alter.chimneys.replace': 'Replace a chimney',
  'alter.decks': 'Add a verandah or deck',
  'alter.decksHigh': 'Add a high verandah or deck',
  'alter.drains': 'Work on drains',
  'alter.equipment': 'Install equipment',
  'alter.equipment.airConditioning': 'Install an air conditioning unit',
  'alter.equipment.alarm': 'Install a security alarm',
  'alter.equipment.antennae': 'Install a satellite dish or aerial',
  'alter.equipment.antennae.aerial': 'Install an aerial antennea',
  'alter.equipment.antennae.dish': 'Install a satellite dish',
  'alter.equipment.bbq': 'Install a barbeque',
  'alter.equipment.biomass': 'Install a flue with a biomass burner',
  'alter.equipment.cctv': 'Install CCTV cameras',
  'alter.equipment.charging': 'Install a car charging point',
  'alter.equipment.heatPump': 'Install a heat pump',
  'alter.equipment.heatPump.air': 'Install an air heat pump',
  'alter.equipment.heatPump.ground': 'Install a ground heat pump',
  'alter.equipment.heatPump.water': 'Install a water heat pump',
  'alter.equipment.industrial': 'Install industrial equipment',
  'alter.equipment.lighting': 'Install outdoor lights',
  'alter.equipment.machinery': 'Install machinery',
  'alter.equipment.solar': 'Install solar panels',
  'alter.equipment.solar.pv': 'Install solar photovoltaics (PV)',
  'alter.equipment.solar.thermal': 'Install solar thermal equipment',
  'alter.equipment.tank': 'Install an outdoor tank (for example a water tank)',
  'alter.equipment.ventilation': 'Install ventilation',
  'alter.equipment.wifi': 'Install internet equipment',
  'alter.equipment.wind': 'Install a wind turbine',
  'alter.facades': 'Change the material or colour of the external walls',
  'alter.facades.insulation': 'Change the insulation of the facade',
  'alter.facades.paint': 'Paint the facade',
  'alter.facades.rear':
    'Change the material or colour of the external walls to the rear of the building',
  'alter.facades.reclad': 'Change the cladding of the facade',
  'alter.facades.repair': 'Repair the facade',
  'alter.highways':
    'Changes to a public road, pavement or path (including drop kerb)',
  'alter.highways.access': 'Create a point of access to a highway',
  'alter.highways.access.unclassified':
    'Create a point of access to an unclassified road',
  'alter.highways.dropKerb': 'Changes to a dropped kerb',
  'alter.highways.droppedKerb': 'Changes to a dropped kerb',
  'alter.highways.droppedKerb.add': 'Add a dropped kerb',
  'alter.highways.droppedKerb.remove': 'Remove a dropped kerb',
  'alter.highways.road': 'Changes to a road',
  'alter.highways.road.add': 'Add a road',
  'alter.highways.road.remove': 'Remove a road',
  'alter.industrial.plant': 'Install plant equipment or machinery',
  'alter.internal': 'Changes to internal walls or layout',
  'alter.landscape': 'Landscaping works',
  'alter.landscape.gardens': 'Add or remove a residential lawn or garden',
  'alter.landscape.ponds': 'Add or remove a pond',
  'alter.openings': 'Change a door or window opening',
  'alter.openings.add': 'Add a door or window opening',
  'alter.openings.add.door': 'Add one or more new doorways',
  'alter.openings.add.door.front':
    'Add new doorways to the front of the building',
  'alter.openings.add.door.rear':
    'Add new doorways to the rear of the building',
  'alter.openings.add.door.side':
    'Add new doorways to the side of the building',
  'alter.openings.add.window': 'Add one or more new windows',
  'alter.openings.add.windows': 'Add one or more new windows',
  'alter.openings.add.windows.front':
    'Add new windows to the front of the building',
  'alter.openings.add.windows.high': 'Add new windows 1.7m up or higher',
  'alter.openings.add.windows.rear':
    'Add new windows to the rear of the building',
  'alter.openings.add.windows.shutters': 'Add new shutters to windows',
  'alter.openings.add.windows.side':
    'Add new windows to the side of the building',
  'alter.openings.alter': 'Change the size of doorways or windows',
  'alter.openings.alter.convert.doorToWindow':
    'Convert a doorway into a window',
  'alter.openings.alter.convert.windowToDoor':
    'Convert a window into a doorway',
  'alter.openings.alter.enlarge.door': 'Enlarge a door opening',
  'alter.openings.alter.enlarge.window': 'Enlarge a window opening',
  'alter.openings.alter.enlarge.window.front':
    'Enlarge a window opening on the front of a building',
  'alter.openings.alter.enlarge.window.rear':
    'Enlarge a window opening on the rear of a building',
  'alter.openings.alter.enlarge.window.side':
    'Enlarge a window opening on the side of a building',
  'alter.openings.alter.reduce.door': 'Reduce the size of a door opening',
  'alter.openings.alter.reduce.window': 'Reduce the size of a window opening',
  'alter.openings.alter.reduce.window.front':
    'Reduce the size of a window opening on the front of a building',
  'alter.openings.alter.reduce.window.rear':
    'Reduce the size of a window opening on the rear of a building',
  'alter.openings.alter.reduce.window.side':
    'Reduce the size of a window opening on the side of a building',
  'alter.openings.remove': 'Block up doorways or windows',
  'alter.openings.remove.door': 'Block up doorways',
  'alter.openings.remove.window': 'Block up windows',
  'alter.pipes': 'Install pipes',
  'alter.remove': 'Remove part of a building (such as a decorative feature)',
  'alter.remove.chimney': 'Remove a chimney',
  'alter.remove.deck': 'Remove a deck',
  'alter.remove.drain': 'Remove a drain',
  'alter.remove.equipment': 'Remove energy equipment',
  'alter.remove.facade': 'Remove part of a facade',
  'alter.remove.soilPipe': 'Remove a soil pipe',
  'alter.remove.surface': 'Remove a hard surface',
  'alter.repair': 'Repair windows or doors',
  'alter.repair.doors': 'Repair doors',
  'alter.repair.windows': 'Repair windows',
  'alter.replace': 'Replace windows or doors',
  'alter.replace.doorsToDoors': 'Replace door with door',
  'alter.replace.doorsToDoors.front':
    'Replace door with door on the front of a building',
  'alter.replace.doorsToDoors.rear':
    'Replace door with door on the rear of a building',
  'alter.replace.doorsToDoors.side':
    'Replace door with door on the side of a building',
  'alter.replace.doorsToWindows': 'Replace door with window',
  'alter.replace.doorsToWindows.front':
    'Replace door with window on the front of a building',
  'alter.replace.doorsToWindows.rear':
    'Replace door with winoow on the rear of a building',
  'alter.replace.doorsToWindows.side':
    'Replace door with window on the side of a building',
  'alter.replace.windowsToDoors': 'Replace window with door',
  'alter.replace.windowsToDoors.front':
    'Replace window with door on the front of a building',
  'alter.replace.windowsToDoors.rear':
    'Replace window with door on the rear of a building',
  'alter.replace.windowsToDoors.side':
    'Replace window with door on the side of a building',
  'alter.replace.windowsToWindows': 'Replace window with window',
  'alter.replace.windowsToWindows.front':
    'Replace window with window on the front ofa building',
  'alter.replace.windowsToWindows.rear':
    'Replace window with window on the rear of a building',
  'alter.replace.windowsToWindows.side':
    'Replace window with window on the side of a building',
  'alter.roof': 'Change the roof',
  'alter.roof.materials': 'Replace or change the roof materials',
  'alter.roof.parapet': 'Add or change a roof parapet',
  'alter.roof.roofTerrace': 'Add a roof terrace',
  'alter.roof.shape': 'Change the shape of a roof',
  'alter.rooflight': 'Add skylights to an existing roof',
  'alter.secondaryGlazing': 'Add secondary glazing to a window',
  'alter.shopfronts': 'Add or alter shop fronts',
  'alter.shutters': 'Add or alter shutters',
  'alter.sign': 'Add an advert or sign',
  'alter.soilPipes': 'Add or replace a soil pipe',
  'alter.staircase': 'Add or change an external staircase',
  'alter.surfaceLow': 'Add a low surface',
  'alter.surfaces': 'Add a decked area or patio',
  'alter.surfaces.deck': 'Add a decked area',
  'alter.surfaces.parking': 'Add a driveway or parking area',
  'alter.surfaces.parking.extend': 'Extend a driveway or parking area',
  'alter.surfaces.parking.new': 'Add a new driveway or parking area',
  'alter.surfaces.parking.replace': 'Replace a driveway or parking area',
  'alter.surfaces.patio': 'Add a patio',
  'alter.surfaces.patio.extend': 'Extend a patio',
  'alter.surfaces.patio.new': 'Add a new patio',
  'alter.surfaces.patio.replace': 'Replace a patio',
  'alter.swimmingPool': 'Install a swimming pool',
  'alter.swimmingPool.indoor': 'Install an indoor swimming pool',
  'alter.swimmingPool.outdoor': 'Install an outdoor swimming pool',
  'alter.trees': 'Changes to trees or hedges',
  'alter.trees.hedge': 'Changes to hedges',
  'alter.trees.hedge.letGrow': 'Let hedges grow',
  'alter.trees.hedge.new': 'New hedges',
  'alter.trees.hedge.prune': 'Prune hedges',
  'alter.trees.hedge.remove': 'Remove hedges',
  'alter.trees.tree': 'Changes to trees',
  'alter.trees.tree.new': 'New trees',
  'alter.trees.tree.prune': 'Prune trees',
  'alter.trees.tree.remove': 'Remove trees',
  changeOfUse: 'Change the use of a building',
  'changeOfUse.annexe':
    'Convert part of the property into a  granny flat (residential annexe)',
  'changeOfUse.caravans': 'Use a caravan or mobile home on the property',
  'changeOfUse.extension': 'Convert an extension',
  'changeOfUse.garage': 'Convert a garage',
  'changeOfUse.land': 'Change the use of land',
  'changeOfUse.let.part': 'Let a part of the property',
  'changeOfUse.let.whole': 'Let the property',
  'changeOfUse.outbuilding':
    'Convert or change the use of an outbuilding (such as a shed, garage or barn)',
  'changeOfUse.part': 'Convert or change the use of part of a building',
  'changeOfUse.property': 'Change the use of a property',
  'changeOfUse.whole': 'Convert or change the use of a whole building',
  'changeOfUse.whole.homeToHMO': 'Convert a home to bedsits or a shared home',
  'changeOfUse.workFromHome': 'Work from home',
  demolish: 'Demolish a building',
  'demolish.boundary': 'Demolish a fence, gate or boundary wall',
  'demolish.full': 'Total demolition of a building',
  'demolish.internal': 'Demolish internal walls',
  'demolish.listed': 'Demolish a listed building',
  'demolish.listed.full': 'Total demolition of a isted building',
  'demolish.listed.part': 'Demolish part of a listed building',
  'demolish.outbuilding': 'Demolish an outbuilding (such as a garage or barn)',
  'demolish.outbuilding.full':
    'Total demolition of an outbuilding (such as a garage or barn)',
  'demolish.outbuilding.part':
    'Demolish part of an outbuilding (such as a garage or barn)',
  'demolish.part': 'Demolish part of a building (such as an extension)',
  'demolish.part.conservatory': 'Demolish part of a conservatory',
  'demolish.replace': 'Demolish a building and build homes in its place',
  extend: 'Extend a building or add an outbuilding',
  'extend.balcony': 'Enlarge a balcony',
  'extend.basement': 'Add a basement extension',
  'extend.basement.extend': 'Enlarge a basement',
  'extend.basement.lightwell': 'Add a lightwell',
  'extend.basement.new': 'Add a new basement extension',
  'extend.front': 'Add a front extension',
  'extend.outbuilding':
    'Add an outbuilding (such as a shed, garage or garden office)',
  'extend.outbuilding.animals':
    'Add an outbuilding - animal enclosure, aviary or beehive',
  'extend.outbuilding.annexe':
    'Add an outbuilding - residential (or "granny") annexe',
  'extend.outbuilding.bedroom': 'Add an outbuilding - bedroom or guest room',
  'extend.outbuilding.games': 'Add an outbuilding - games room',
  'extend.outbuilding.garage': 'Add an outbuilding - garage',
  'extend.outbuilding.greenhouse': 'Add an outbuilding - greenhouse',
  'extend.outbuilding.gym': 'Add an outbuilding - gym',
  'extend.outbuilding.office': 'Add an outbuilding - office',
  'extend.outbuilding.other': 'Add an outbuilding - something else',
  'extend.outbuilding.play': 'Add an outbuilding - play house',
  'extend.outbuilding.sauna': 'Add an outbuilding - sauna',
  'extend.outbuilding.shed': 'Add an outbuilding - shed',
  'extend.outbuilding.shelter':
    'Add an outbuilding - car parking or smoking shelter',
  'extend.outbuilding.store': 'Add an outbuilding - storage',
  'extend.outbuilding.studio': 'Add an outbuilding - studio',
  'extend.outbuilding.summerHouse': 'Add an outbuilding - summer house',
  'extend.outbuilding.swimmingPool': 'Add an outbuilding - swimming pool',
  'extend.outbuilding.tank': 'Add an outbuilding - tank',
  'extend.outbuilding.workshop': 'Add an outbuilding - workshop',
  'extend.porch': 'Add a porch',
  'extend.porch.front': 'Add a porch to the front of the building',
  'extend.porch.rear': 'Add a porch to the rear of the building',
  'extend.porch.side': 'Add a porch to the side of the building',
  'extend.rear': 'Add a rear or side extension (or conservatory)',
  'extend.rear.rear': 'Add a rear extension',
  'extend.rear.side': 'Add a side extension',
  'extend.roof': 'Add a roof extension',
  'extend.roof.connect': 'Join two roofs',
  'extend.roof.dormer': 'Add a roof dormer',
  'extend.roof.dormer.front': 'Add a roof dormer to the front of the building',
  'extend.roof.dormer.frontAndRear':
    'Add a roof dormer to the front and rear of the building',
  'extend.roof.dormer.mansard': 'Add a mansard roof',
  'extend.roof.dormer.rear': 'Add a roof dormer to the rear of the building',
  'extend.roof.dormer.side': 'Add a roof dormer to the side of the building',
  'extend.roof.hiptogable': 'Convert a hip roof to a gable',
  'extend.roof.hipToGable': 'Convert a hip roof to a gable',
  'extend.roof.mansard': 'Convert to a mansard roof',
  'extend.roof.newstorey': 'Add one or more new storeys',
  'extend.roof.newStorey': 'Add one or more new storeys',
  'extend.roof.slope': 'Convert to a sloping roof',
  'extend.side': 'Add a side extension',
  'extend.upperStorey': 'Add an upper storey extension',
  internal: 'Internal building works, such as change the internal layout',
  'internal.doorways': 'Alter internal doors',
  'internal.finishes': 'Alter internal finishes',
  'internal.floors': 'Alter internal floors',
  'internal.loft': 'Convert a loft',
  'internal.mezzanine': 'Add a mezzanine floor',
  'internal.staircases': 'Alter internal staircases',
  'internal.walls': 'Alter internal walls',
  'internal.windows.openings': 'Alter internal window openings',
  maintain: 'Maintenance of an existing structure',
  new: 'Add a new separate building or self-contained units',
  'new.agriculture': 'New agricultural buildings',
  'new.agriculture.glasshouse': 'New agricultural buildings - glasshouse',
  'new.agriculture.mining': 'New agricultural buildings - mining',
  'new.agriculture.pigs': 'New agricultural buildings - pigs',
  'new agriculture.poultry': 'New agricultural buildings - poultry',
  'new.clickCollect': 'Install click and collect facilities',
  'new.dwelling': 'New, self-contained dwelling',
  'new.dwelling.flat': 'New flats',
  'new.dwelling.house': 'New houses',
  'new.forestry': 'Build new forestry buildings',
  'new.industrial': 'New industrial premises',
  'new.industrial.waste': 'New waste disposal facilities',
  'new.leisure': 'New leisure premises',
  'new.office': 'New offices',
  'new.other': 'Add another type of building - something else',
  'new.residential.dwelling': 'Build new homes',
  'new.retail': 'New retail premises',
  'new.telecoms': 'Install telecommunications equipment',
  'new.temporaryStructure': 'Build a temporary structure',
  'new.warehouse': 'New storage or distribution premises',
  not: 'Negate a project type',
  'not.alter.replace': 'Do not add or change windows or doors',
  'not.alter.rooflight': 'Do not add or change a rooflight',
  'not.dropKerb': 'Do not add or change a dropped kerb',
  repair: 'Repairs',
  'repair.historicFabric': 'Repair the historic fabric',
  other: 'Other project type',
  unit: 'Change of units',
  'unit.merge': 'Convert two or more properties into one',
  'unit.subdivide': 'Convert a home or part of a home into flats',
};

type ProjectTypeKeys = keyof typeof ProjectTypes;

type GenericProjectType<TKey extends ProjectTypeKeys> = {
  value: TKey;
  description: (typeof ProjectTypes)[TKey];
};

type ProjectTypeMap = {
  [K in ProjectTypeKeys]: GenericProjectType<K>;
};

/**
 * @id #ProjectType
 * @description Planning project types
 */
export type ProjectType = ProjectTypeMap[keyof ProjectTypeMap];
