/**
 * Values of `data.proposal.projectType`
 */
export const ProjectTypes = {
  alter: 'Alter a building',
  'alter.balcony': 'Add or alter a balcony',
  'alter.bayWindow': 'Add or remove a bay window',
  'alter.bayWindow.add': 'Add a bay window',
  'alter.bayWindow.rear': 'Add a bay window to the rear of the building',
  'alter.bayWindow.remove': 'Remove a bay window',
  'alter.boundary': 'Changes to a fence, wall or gate',
  'alter.boundary.add': 'Add a new fence, wall or gate',
  'alter.boundary.add.fence': 'Add a new fence',
  'alter.boundary.add.gate': 'Add a new gate',
  'alter.boundary.add.wall': 'Add a new boundary wall',
  'alter.boundary.repair': 'Repair a fence, wall or gate',
  'alter.boundary.repair.fence': 'Repair a fence',
  'alter.boundary.repair.gate': 'Repair a gate',
  'alter.boundary.repair.wall': 'Repair a wall',
  'alter.boundary.replace': 'Replace a fence, wall or gate',
  'alter.boundary.replace.fence': 'Replace a fence',
  'alter.boundary.replace.gate': 'Replace a gate',
  'alter.boundary.replace.wall': 'Replace a wall',
  'alter.cables': 'Install underground cables',
  'alter.chimneys': 'Change chimneys',
  'alter.chimneys.add': 'Add a chimney',
  'alter.chimneys.replace': 'Replace a chimney',
  'alter.deck': 'Add a verandah or deck',
  'alter.drains': 'Work on drains',
  'alter.equipment': 'Install equipment',
  'alter.equipment.airConditioning': 'Install an air conditioning unit',
  'alter.equipment.alarm': 'Install a security alarm',
  'alter.equipment.antennae': 'Install a satellite dish or aerial',
  'alter.equipment.antennae.aerial': 'Install an aerial antennea',
  'alter.equipment.antennae.dish': 'Install a satellite dish',
  'alter.equipment.bbq': 'Install a barbeque',
  'alter.equipment.biomass': 'Install a flue with a biomass burner',
  'alter.equipment.cctv': 'Install CCTV cameras',
  'alter.equipment.charging': 'Install a car charging point',
  'alter.equipment.heatPump': 'Install a heat pump',
  'alter.equipment.heatPump.air': 'Install an air heat pump',
  'alter.equipment.heatPump.ground': 'Install a ground heat pump',
  'alter.equipment.heatPump.water': 'Install a water heat pump',
  'alter.equipment.industrial': 'Install industrial equipment',
  'alter.equipment.lighting': 'Install outdoor lights',
  'alter.equipment.solar': 'Install solar panels',
  'alter.equipment.solar.pv': 'Install solar photovoltaics (PV)',
  'alter.equipment.solar.thermal': 'Install solar thermal equipment',
  'alter.equipment.tank': 'Install an outdoor tank (for example a water tank)',
  'alter.equipment.wifi': 'Install internet equipment',
  'alter.equipment.wind': 'Install a wind turbine',
  'alter.facades': 'Change the material or colour of the external walls',
  'alter.facades.paint': 'Paint the facade',
  'alter.facades.rear':
    'Change the material or colour of the external walls to the rear of the building',
  'alter.facades.reclad': 'Change the cladding of the facade',
  'alter.highways':
    'Changes to a public road, pavement or path (including drop kerb)',
  'alter.highways.access': 'Create a point of access to a highway',
  'alter.highways.access.unclassified':
    'Create a point of access to an unclassified road',
  'alter.highways.droppedKerb': 'Changes to a dropped kerb',
  'alter.highways.droppedKerb.add': 'Add a dropped kerb',
  'alter.highways.droppedKerb.remove': 'Remove a dropped kerb',
  'alter.landscape': 'Landscaping works',
  'alter.landscape.gardens': 'Add or remove a residential lawn or garden',
  'alter.landscape.ponds': 'Add or remove a pond',
  'alter.openings': 'Change a door or window opening',
  'alter.openings.add': 'Add a door or window opening',
  'alter.openings.add.door': 'Add one or more new doorways',
  'alter.openings.add.door.front':
    'Add new doorways to the front of the building',
  'alter.openings.add.door.rear':
    'Add new doorways to the rear of the building',
  'alter.openings.add.door.side':
    'Add new doorways to the side of the building',
  'alter.openings.add.window': 'Add one or more new windows',
  'alter.openings.add.window.front':
    'Add new windows to the front of the building',
  'alter.openings.add.window.high': 'Add new windows 1.7m up or higher',
  'alter.openings.add.window.rear':
    'Add new windows to the rear of the building',
  'alter.openings.add.window.shutters': 'Add new shutters to windows',
  'alter.openings.add.window.side':
    'Add new windows to the side of the building',
  'alter.openings.alter': 'Change the size of doorways or windows',
  'alter.openings.alter.convert.doorToWindow':
    'Convert a doorway into a window',
  'alter.openings.alter.convert.windowToDoor':
    'Convert a window into a doorway',
  'alter.openings.alter.enlarge.door': 'Enlarge a door opening',
  'alter.openings.alter.enlarge.window': 'Enlarge a window opening',
  'alter.openings.alter.reduce.door': 'Reduce the size of a door opening',
  'alter.openings.alter.reduce.window': 'Reduce the size of a window opening',
  'alter.openings.remove': 'Block up doorways or windows',
  'alter.pipes': 'Install pipes',
  'alter.remove': 'Remove part of a building (such as a decorative feature)',
  'alter.remove.chimney': 'Remove a chimney',
  'alter.remove.deck': 'Remove a deck',
  'alter.remove.equipment': 'Remove energy equipment',
  'alter.remove.facade': 'Remove part of a facade',
  'alter.remove.soilPipe': 'Remove a soil pipe',
  'alter.remove.surface': 'Remove a hard surface',
  'alter.repair': 'Repair windows or doors',
  'alter.repair.doors': 'Repair doors',
  'alter.repair.windows': 'Repair windows',
  'alter.replace': 'Replace windows or doors',
  'alter.replace.doorsToDoors': 'Replace door with door',
  'alter.replace.doorsToWindows': 'Replace door with window',
  'alter.replace.windowsToDoors': 'Replace window with door',
  'alter.replace.windowsToWindows': 'Replace window with window',
  'alter.roof': 'Change the roof',
  'alter.roof.materials': 'Replace or change the roof materials',
  'alter.roof.parapet': 'Add or change a roof parapet',
  'alter.roof.roofTerrace': 'Add a roof terrace',
  'alter.roof.shape': 'Change the shape of a roof',
  'alter.rooflight': 'Add skylights to an existing roof',
  'alter.secondaryGlazing': 'Add secondary glazing to a window',
  'alter.shopfronts': 'Add or alter shop fronts',
  'alter.shutters': 'Add or alter shutters',
  'alter.sign': 'Add an advert or sign',
  'alter.soilPipes': 'Add or replace a soil pipe',
  'alter.staircase': 'Add or change an external staircase',
  'alter.surfaces': 'Add a decked area or patio',
  'alter.surfaces.parking': 'Add a driveway or parking area',
  'alter.swimmingPool': 'Install a swimming pool',
  'alter.swimmingPool.indoor': 'Install an indoor swimming pool',
  'alter.swimmingPool.outdoor': 'Install an outdoor swimming pool',
  'alter.trees': 'Changes to trees or hedges',
  changeOfUse: 'Change the use of a building',
  'changeofUse.annexe':
    'Convert part of the property into a  granny flat (residential annexe)',
  'changeOfUse.caravans': 'Use a caravan or mobile home on the property',
  'changeOfUse.garage': 'Convert a garage',
  'changeOfUse.let.part': 'Let a part of the property',
  'changeOfUse.let.whole': 'Let the property',
  'changeOfUse.outbuilding':
    'Convert or change the use of an outbuilding (such as a shed, garage or barn)',
  'changeOfUse.part': 'Convert or change the use of part of a building',
  'changeOfUse.whole.homeToHMO': 'Convert a home to bedsits or a shared home',
  'changeOfUse.whole': 'Change the use of a property',
  'changeOfUse.workFromHome': 'Work from home',
  demolish: 'Demolish a building',
  'demolish.boundary': 'Demolish a fence, gate or boundary wall',
  'demolish.full': 'Demolish a building',
  'demolish.outbuildings': 'Demolish an outbuilding (such as a garage or barn)',
  'demolish.part': 'Demolish part of a building (such as an extension)',
  'demolish.replace': 'Demolish a building and build homes in its place',
  extend: 'Extend a building or add an outbuilding',
  'extend.basement': 'Add a basement extension',
  'extend.basement.extend': 'Enlarge a basement',
  'extend.basement.lightwell': 'Add a lightwell',
  'extend.front': 'Add a front extension',
  'extend.outbuildings':
    'Add an outbuilding (such as a shed, garage or garden office)',
  'extend.outbuildings.animals':
    'Add an outbuilding - animal enclosure, aviary or beehive',
  'extend.outbuildings.annexe':
    'Add an outbuilding - residential (or "granny") annexe',
  'extend.outbuildings.bedroom': 'Add an outbuilding - bedroom or guest room',
  'extend.outbuildings.games': 'Add an outbuilding - games room',
  'extend.outbuildings.garage': 'Add an outbuilding - garage',
  'extend.outbuildings.greenhouse': 'Add an outbuilding - greenhouse',
  'extend.outbuildings.gym': 'Add an outbuilding - gym',
  'extend.outbuildings.office': 'Add an outbuilding - office',
  'extend.outbuildings.other': 'Add an outbuilding - something else',
  'extend.outbuildings.sauna': 'Add an outbuilding - sauna',
  'extend.outbuildings.shed': 'Add an outbuilding - shed',
  'extend.outbuildings.shelter':
    'Add an outbuilding - car parking or smoking shelter',
  'extend.outbuildings.store': 'Add an outbuilding - storage',
  'extend.outbuildings.studio': 'Add an outbuilding - studio',
  'extend.outbuildings.summerHouse': 'Add an outbuilding - summer house',
  'extend.outbuildings.swimmingPool': 'Add an outbuilding - swimming pool',
  'extend.outbuildings.tank': 'Add an outbuilding - tank',
  'extend.outbuildings.workshop': 'Add an outbuilding - workshop',
  'extend.porch': 'Add a porch',
  'extend.porch.front': 'Add a porch to the front of the building',
  'extend.porch.rear': 'Add a porch to the rear of the building',
  'extend.porch.side': 'Add a porch to the side of the building',
  'extend.rear': 'Add a rear or side extension (or conservatory)',
  'extend.rear.rear': 'Add a rear extension',
  'extend.rear.side': 'Add a side extension',
  'extend.roof': 'Add a roof extension',
  'extend.roof.dormer': 'Add a roof dormer',
  'extend.roof.dormer.front': 'Add a roof dormer to the front of the building',
  'extend.roof.dormer.frontAndRear':
    'Add a roof dormer to the front and rear of the building',
  'extend.roof.dormer.mansard': 'Add a mansard roof',
  'extend.roof.dormer.rear': 'Add a roof dormer to the rear of the building',
  'extend.roof.dormer.side': 'Add a roof dormer to the side of the building',
  'extend.roof.hipToGable': 'Hip-to-gable roof enlargement',
  'exend.roof.newStorey': 'Add one or more new storeys',
  'extend.upperStorey': 'Add an upper storey extension',
  internal: 'Internal building works, such as change the internal layout',
  'internal.doorways': 'Alter internal doors',
  'internal.finishes': 'Alter internal finishes',
  'internal.floors': 'Alter internal floors',
  'internal.loft': 'Convert a loft',
  'internal.mezzanine': 'Add a mezzanine floor',
  'internal.staircases': 'Alter internal staircases',
  'internal.walls': 'Alter internal walls',
  'internal.windows.openings': 'Alter internal window openings',
  new: 'Add another type of building',
  'new.agriculture': 'Agricultural buildings',
  'new.agriculture.glassHouse': 'Agricultural buildings - glass house',
  'new.agriculture.mining': 'Agricultural buildings - mining',
  'new.agriculture.pigs': 'Agricultural buildings - pigs',
  'new agriculture.poultry': 'Agricultural buildings - poultry',
  'new.clickCollect': 'Install click and collect facilities',
  'new.dwelling': 'New, self-contained dwelling',
  'new.dwelling.flat': 'New flats',
  'new.dwelling.house': 'New houses',
  'new.forestry': 'Build new forestry buildings',
  'new.industrial': 'Industrial premises',
  'new.leisure': 'Leisure premises',
  'new.office': 'Offices',
  'new.residential.dwelling': 'Build new homes on a roof',
  'new.retail': 'Retail premises',
  'new.telecoms': 'Install telecommunications equipment',
  'new.temporaryStructure':
    'Erect a temporary structure for historic visitor attractions and listed buildings',
  'new.warehouse': 'Storage or distribution premises',
  unit: 'Change of units',
  'unit.merge': 'Convert two or more properties into one',
  'unit.subdivide': 'Convert a home or part of a home into flats',
};
