/**
 * Values of `data.property.type`, derived from Basic Land and Property Unit (BLPU) classification codes
 */
export const PropertyTypes = {
  commercial: 'Commercial',
  'commercial.agriculture': 'Agricultural',
  'commercial.agriculture.farm': 'Farm / Non-Residential Associated Building',
  'commercial.fish': 'Fishery',
  'commercial.fish.farm': 'Fish Farming',
  'commercial.fish.hatchery': 'Fish Hatchery',
  'commercial.fish.processing': 'Fish Processing',
  'commercial.fish.oysters': 'Oyster / Mussel Bed',
  'commercial.horticulture': 'Horticulture',
  'commercial.horticulture.smallholding': 'Smallholding',
  'commercial.horticulture.vineyard': 'Vineyard',
  'commercial.horticulture.watercress': 'Watercress Bed',
  'commercial.abattoir': 'Slaughter House / Abattoir',
  'commercial.ancilliary': 'Ancillary Building',
  'commercial.community': 'Community Services',
  'commercial.community.court': 'Law Court',
  'commercial.community.prison': 'Prison',
  'commercial.community.prison.detention': 'HM Detention Centre',
  'commercial.community.prison.service': 'HM Prison Service',
  'commercial.community.prison.secureResidential':
    'Secure Residential Accommodation',
  'commercial.community.hall':
    'Public / Village Hall / Other Community Facility',
  'commercial.community.hall.club': 'Youth Recreational / Social Club',
  'commercial.community.wc': 'Public Convenience',
  'commercial.community.cemetary':
    'Cemetery / Crematorium / Graveyard. In Current Use.',
  'commercial.community.cemetary.columbarium': 'Columbarium',
  'commercial.community.cemetary.crematorium': 'Crematorium',
  'commercial.community.cemetary.chapelOfRest': 'Chapel Of Rest',
  'commercial.community.cemetary.cemetary': 'Cemetery',
  'commercial.community.cemetary.military': 'Military Cemetery',
  'commercial.community.cemetary.mortuary': 'Mortuary',
  'commercial.community.religious':
    'Church Hall / Religious Meeting Place / Hall',
  'commercial.community.services': 'Community Service Centre / Office',
  'commercial.community.HWRC': 'Public Household Waste Recycling Centre (HWRC)',
  'commercial.community.recycling': 'Recycling Site',
  'commercial.community.CCTV': 'CCTV',
  'commercial.community.employment': 'Job Centre',
  'commercial.education': 'Education',
  'commercial.education.college': 'College',
  'commercial.education.college.further': 'Further Education',
  'commercial.education.college.higher': 'Higher Education',
  'commercial.education.nursery': "Children's Nursery / Crèche",
  'commercial.education.school':
    'Preparatory / First / Primary / Infant / Junior / Middle School',
  'commercial.education.school.first': 'First School',
  'commercial.education.school.infant': 'Infant School',
  'commercial.education.school.junior': 'Junior School',
  'commercial.education.school.middle': 'Middle School',
  'commercial.education.school.primary.private':
    'Non State Primary / Preparatory School',
  'commercial.education.school.primary.state': 'Primary School',
  'commercial.education.secondarySchool': 'Secondary / High School',
  'commercial.education.secondarySchool.private': 'Non State Secondary School',
  'commercial.education.secondarySchool.state': 'Secondary School',
  'commercial.education.university': 'University',
  'commercial.education.specialNeeds': 'Special Needs Establishment.',
  'commercial.education.other': 'Other Educational Establishment',
  'commercial.guest': 'Hotel / Motel / Boarding / Guest House',
  'commercial.guest.hostel':
    'Boarding / Guest House / Bed And Breakfast / Youth Hostel',
  'commercial.guest.hostel.youth': 'Youth Hostel',
  'commercial.guest.shortLet':
    'Holiday Let/Accomodation/Short-Term Let Other Than CH01',
  'commercial.guest.hotel': 'Hotel/Motel',
  'commercial.industrial':
    'Industrial Applicable to manufacturing, engineering, maintenance, storage / wholesale distribution and extraction sites',
  'commercial.industrial.manufacturing': 'Factory/Manufacturing',
  'commercial.industrial.manufacturing.aircraft': 'Aircraft Works',
  'commercial.industrial.manufacturing.boats': 'Boat Building',
  'commercial.industrial.manufacturing.bricks': 'Brick Works',
  'commercial.industrial.manufacturing.beer': 'Brewery',
  'commercial.industrial.manufacturing.cider': 'Cider Manufacture',
  'commercial.industrial.manufacturing.chemicals': 'Chemical Works',
  'commercial.industrial.manufacturing.cement': 'Cement Works',
  'commercial.industrial.manufacturing.dairy': 'Dairy Processing',
  'commercial.industrial.manufacturing.distillery': 'Distillery',
  'commercial.industrial.manufacturing.flour': 'Flour Mill',
  'commercial.industrial.manufacturing.food': 'Food Processing',
  'commercial.industrial.manufacturing.glass': 'Glassworks',
  'commercial.industrial.manufacturing.other': 'Manufacturing',
  'commercial.industrial.manufacturing.hops': 'Oast House',
  'commercial.industrial.manufacturing.oil': 'Oil Refining',
  'commercial.industrial.manufacturing.pottery': 'Pottery Manufacturing',
  'commercial.industrial.manufacturing.paper': 'Paper Mill',
  'commercial.industrial.manufacturing.printing': 'Printing Works',
  'commercial.industrial.manufacturing.sugar': 'Sugar Refinery',
  'commercial.industrial.manufacturing.steel': 'Steel Works',
  'commercial.industrial.manufacturing.timber': 'Timber Mill',
  'commercial.industrial.manufacturing.wine': 'Winery',
  'commercial.industrial.manufacturing.ships': 'Shipyard',
  'commercial.industrial.extraction': 'Mineral / Ore Working / Quarry / Mine',
  'commercial.industrial.extraction.mining': 'Mineral Mining / Active',
  'commercial.industrial.extraction.distribution':
    'Mineral Distribution / Storage',
  'commercial.industrial.extraction.processing': 'Mineral Processing',
  'commercial.industrial.extraction.oilGas': 'Oil / Gas Extraction / Active',
  'commercial.industrial.extraction.quarrying':
    'Mineral Quarrying / Open Extraction / Active',
  'commercial.industrial.light': 'Workshop / Light Industrial',
  'commercial.industrial.light.garage': 'Servicing Garage',
  'commercial.industrial.light.storage': 'Warehouse / Store / Storage Depot',
  'commercial.industrial.light.storage.crops': 'Crop Handling / Storage',
  'commercial.industrial.light.storage.post': 'Postal Sorting / Distribution',
  'commercial.industrial.light.storage.solidFuel': 'Solid Fuel Storage',
  'commercial.industrial.light.storage.timber': 'Timber Storage',
  'commercial.industrial.distribution': 'Wholesale Distribution',
  'commercial.industrial.distribution.solidFueld': 'Solid Fuel Distribution',
  'commercial.industrial.distribution.timber': 'Timber Distribution',
  'commercial.industrial.recycling': 'Recycling Plant',
  'commercial.industrial.incineration': 'Incinerator / Waste Transfer Station',
  'commercial.industrial.maintenanceDepot': 'Maintenance Depot',
  'commercial.leisure':
    'Leisure - Applicable to recreational sites and enterprises',
  'commercial.leisure.amusements': 'Amusements',
  'commercial.leisure.amusements.pier': 'Leisure Pier',
  'commercial.leisure.holiday': 'Holiday / Campsite',
  'commercial.leisure.holiday.camping': 'Camping',
  'commercial.leisure.holiday.caravanning': 'Caravanning',
  'commercial.leisure.holiday.accommodation': 'Holiday Accommodation',
  'commercial.leisure.holiday.centre': 'Holiday Centre',
  'commercial.leisure.holiday.youth': 'Youth Organisation Camp',
  'commercial.leisure.library': 'Library',
  'commercial.leisure.library.readingRoom': 'Reading Room',
  'commercial.leisure.museum': 'Museum / Gallery',
  'commercial.leisure.museum.art': 'Art Centre / Gallery',
  'commercial.leisure.museum.aviation': 'Aviation Museum',
  'commercial.leisure.museum.heritage': 'Heritage Centre',
  'commercial.leisure.museum.industrial': 'Industrial Museum',
  'commercial.leisure.museum.military': 'Military Museum',
  'commercial.leisure.museum.maritime': 'Maritime Museum',
  'commercial.leisure.museum.science': 'Science Museum',
  'commercial.leisure.museum.transport': 'Transport Museum',
  'commercial.leisure.sport':
    'Indoor / Outdoor Leisure / Sporting Activity / Centre',
  'commercial.leisure.sport.athletics': 'Athletics Facility',
  'commercial.leisure.sport.bowls': 'Bowls Facility',
  'commercial.leisure.sport.cricket': 'Cricket Facility',
  'commercial.leisure.sport.curling': 'Curling Facility',
  'commercial.leisure.sport.swimming': 'Diving / Swimming Facility',
  'commercial.leisure.sport.equestrian': 'Equestrian Sports Facility',
  'commercial.leisure.sport.football': 'Football Facility',
  'commercial.leisure.sport.fishing': 'Fishing / Angling Facility',
  'commercial.leisure.sport.golf': 'Golf Facility',
  'commercial.leisure.sport.gliding': 'Gliding Facility',
  'commercial.leisure.sport.dogracing': 'Greyhound Racing Facility',
  'commercial.leisure.sport.hockey': 'Hockey Facility',
  'commercial.leisure.sport.horseracing': 'Horse Racing Facility',
  'commercial.leisure.sport.historicVehicles':
    'Historic Vessel / Aircraft / Vehicle',
  'commercial.leisure.sport.centre': 'Activity / Leisure / Sports Centre',
  'commercial.leisure.sport.model': 'Model Sports Facility',
  'commercial.leisure.sport.motor': 'Motor Sports Facility',
  'commercial.leisure.sport.playingField': 'Playing Field',
  'commercial.leisure.sport.racquet': 'Racquet Sports Facility',
  'commercial.leisure.sport.rugby': 'Rugby Facility',
  'commercial.leisure.sport.recreationGround': 'Recreation Ground',
  'commercial.leisure.sport.shinty': 'Shinty Facility',
  'commercial.leisure.sport.skateboarding': 'Skateboarding Facility',
  'commercial.leisure.sport.firing': 'Civilian Firing Facility',
  'commercial.leisure.sport.tenpin': 'Tenpin Bowling Facility',
  'commercial.leisure.sport.tennis': 'Public Tennis Court',
  'commercial.leisure.sport.water': 'Water Sports Facility',
  'commercial.leisure.sport.winter': 'Winter Sports Facility',
  'commercial.leisure.sport.wildlife': 'Wildlife Sports Facility',
  'commercial.leisure.sport.cycling': 'Cycling Sports Facility',
  'commercial.leisure.entertainment':
    'Bingo Hall / Cinema / Conference / Exhibition Centre / Theatre / Concert Hall',
  'commercial.leisure.entertainment.cinema': 'Cinema',
  'commercial.leisure.entertainment.mixed': 'Entertainment Complex',
  'commercial.leisure.entertainment.exhibition':
    'Conference / Exhibition Centre',
  'commercial.leisure.entertainment.theatre': 'Theatre',
  'commercial.leisure.park.zoo': 'Zoo / Theme Park',
  'commercial.leisure.park.amusement': 'Amusement Park',
  'commercial.leisure.park.aquatic': 'Aquatic Attraction',
  'commercial.leisure.park.model': 'Model Village Site',
  'commercial.leisure.park.wildlife': 'Wildlife / Zoological Park',
  'commercial.leisure.beachHut':
    'Beach Hut (Recreational, Non-Residential Use Only)',
  'commercial.leisure.club.private': "Licensed Private Members' Club",
  'commercial.leisure.club.social': 'Recreational / Social Club',
  'commercial.leisure.arena': 'Arena / Stadium',
  'commercial.leisure.arena.stadium': 'Stadium',
  'commercial.leisure.arena.showground': 'Showground',
  'commercial.medical': 'Medical',
  'commercial.medical.dentist': 'Dentist',
  'commercial.medical.GP': 'General Practice Surgery / Clinic',
  'commercial.medical.healthCentre': 'Health Centre',
  'commercial.medical.healthServices': 'Health Care Services',
  'commercial.medical.care': 'Hospital / Hospice',
  'commercial.medical.care.home': 'Care home/Hospice',
  'commercial.medical.care.hospital': 'Hospital',
  'commercial.medical.lab': 'Medical / Testing / Research Laboratory',
  'commercial.medical.professional': 'Professional Medical Service',
  'commercial.medical.assessment': 'Assessment / Development Services',
  'commercial.animals': 'Animal Centre',
  'commercial.animals.kennelsCattery': 'Cattery / Kennel',
  'commercial.animals.services': 'Animal Services',
  'commercial.animals.services.quarantine': 'Animal Quarantining',
  'commercial.animals.equestrian': 'Equestrian',
  'commercial.animals.equestrian.racing': 'Horse Racing / Breeding Stable',
  'commercial.animals.equestrian.riding': 'Commercial Stabling / Riding',
  'commercial.animals.vet': 'Vet / Animal Medical Treatment',
  'commercial.animals.sanctuary': 'Animal / Bird / Marine Sanctuary',
  'commercial.animals.sanctuary.animals': 'Animal Sanctuary',
  'commercial.animals.sanctuary.marine': 'Marine Sanctuary',
  'commercial.office': 'Office',
  'commercial.office.workspace': 'Office / Work Studio',
  'commercial.office.workspace.embassy':
    'Embassy /, High Commission / Consulate',
  'commercial.office.workspace.film': 'Film Studio',
  'commercial.office.workspace.gov.national': 'Central Government Service',
  'commercial.office.workspace.gov.local': 'Local Government Service',
  'commercial.office.broadcasting': 'Broadcasting (TV / Radio)',
  'commercial.retail': 'Retail',
  'commercial.retail.financial': 'Bank / Financial Service',
  'commercial.retail.services': 'Retail Service Agent',
  'commercial.retail.post': 'Post Office',
  'commercial.retail.market': 'Market (Indoor / Outdoor)',
  'commercial.retail.market.fish': 'Fish Market',
  'commercial.retail.market.fruit': 'Fruit / Vegetable Market',
  'commercial.retail.market.livestock': 'Livestock Market',
  'commercial.retail.fuel': 'Petrol Filling Station',
  'commercial.retail.drinking': 'Public House / Bar / Nightclub',
  'commercial.retail.restaurant': 'Restaurant / Cafeteria',
  'commercial.retail.showroom': 'Shop / Showroom',
  'commercial.retail.shop': 'Shop',
  'commercial.retail.shop.gardenCentre': 'Garden Centre',
  'commercial.retail.licensedPremises': 'Other Licensed Premise / Vendor',
  'commercial.retail.takeaway': 'Fast Food Outlet / Takeaway (Hot / Cold)',
  'commercial.retail.atm': 'Automated Teller Machine (ATM)',
  'commercial.storageLand': 'Storage Land',
  'commercial.storageLand.general': 'General Storage Land',
  'commercial.storageLand.building': "Builders' Yard",
  'commercial.transport': 'Transport',
  'commercial.transport.air':
    'Airfield / Airstrip / Airport / Air Transport Infrastructure Facility',
  'commercial.transport.air.airfield': 'Airfield',
  'commercial.transport.air.infrastructure':
    'Air Transport Infrastructure Services',
  'commercial.transport.air.airport': 'Airport',
  'commercial.transport.air.passengerTerminal': 'Air Passenger Terminal',
  'commercial.transport.air.helicopterStation': 'Helicopter Station',
  'commercial.transport.air.heliport': 'Heliport / Helipad',
  'commercial.transport.bus': 'Bus Shelter',
  'commercial.transport.parking':
    'Car / Coach / Commercial Vehicle / Taxi Parking / Park And Ride Site',
  'commercial.transport.parking.parkAndRide': 'Public Park And Ride',
  'commercial.transport.parking.car': 'Public Car Parking',
  'commercial.transport.parking.coach': 'Public Coach Parking',
  'commercial.transport.parking.commercialVehicle':
    'Public Commercial Vehicle Parking',
  'commercial.transport.freight': 'Goods Freight Handling / Terminal',
  'commercial.transport.freight.air': 'Air Freight Terminal',
  'commercial.transport.freight.container': 'Container Freight',
  'commercial.transport.freight.road': 'Road Freight Transport',
  'commercial.transport.freight.rail': 'Rail Freight Transport',
  'commercial.transport.marina': 'Marina',
  'commercial.transport.mooring': 'Mooring',
  'commercial.transport.railAsset': 'Railway Asset',
  'commercial.transport.terminal': 'Station / Interchange / Terminal / Halt',
  'commercial.transport.terminal.bus': 'Bus station',
  'commercial.transport.terminal.train': 'Train station',
  'commercial.transport.terminal.vehicularRail': 'Vehicular Rail Terminal',
  'commercial.transport.track': 'Transport Track / Way',
  'commercial.transport.track.cliff': 'Cliff Railway',
  'commercial.transport.track.cable': 'Chair Lift / Cable Car / Ski Tow',
  'commercial.transport.track.monorail': 'Monorail',
  'commercial.transport.storage': 'Vehicle Storage',
  'commercial.transport.storage.boat': 'Boat Storage',
  'commercial.transport.storage.bus': 'Bus / Coach Depot',
  'commercial.transport.infrastructure': 'Transport Related Infrastructure',
  'commercial.transport.infrastructure.aqueduct': 'Aqueduct',
  'commercial.transport.infrastructure.lock': 'Lock',
  'commercial.transport.infrastructure.weir': 'Weir',
  'commercial.transport.infrastructure.weighing': 'Weighbridge / Load Gauge',
  'commercial.transport.overnightLorryPark': 'Overnight Lorry Park',
  'commercial.transport.dock':
    'Harbour / Port / Dock / Dockyard / Slipway / Landing Stage / Pier / Jetty / Pontoon / Terminal / Berthing / Quay',
  'commercial.transport.dock.ferry.passengers': 'Passenger Ferry Terminal',
  'commercial.transport.dock.generalBerth': 'Non-Tanker Nautical Berthing',
  'commercial.transport.dock.refuelling': 'Nautical Refuelling Facility',
  'commercial.transport.dock.slipway': 'Slipway',
  'commercial.transport.dock.passenger': 'Ship Passenger Terminal',
  'commercial.transport.dock.tankerBerth': 'Tanker Berthing',
  'commercial.transport.dock.ferry.vehicles': 'Vehicular Ferry Terminal',
  'commercial.utility': 'Utility',
  'commercial.utility.SubStation': 'Electricity Sub-Station',
  'commercial.utility.landfill': 'Landfill',
  'commercial.utility.electricity': 'Power Station / Energy Production',
  'commercial.utility.electricity.distribution':
    'Electricity Distribution Facility',
  'commercial.utility.electricity.production':
    'Electricity Production Facility',
  'commercial.utility.electricity.windFarm': 'Wind Farm',
  'commercial.utility.electricity.windTurbine': 'Wind Turbine',
  'commercial.utility.water': 'Pump House / Pumping Station / Water Tower',
  'commercial.utility.water.pump.control': 'Water Controlling / Pumping',
  'commercial.utility.water.pump.distribution': 'Water Distribution / Pumping',
  'commercial.utility.water.qualityMonitoring': 'Water Quality Monitoring',
  'commercial.utility.water.storage': 'Water Storage',
  'commercial.utility.water.waste': 'Waste Water Distribution / Pumping',
  'commercial.utility.telecoms': 'Telecommunication',
  'commercial.utility.telecoms.mast': 'Telecommunications Mast',
  'commercial.utility.telecoms.exhange': 'Telephone Exchange',
  'commercial.utility.waterTreatment':
    'Water / Waste Water / Sewage Treatment Works',
  'commercial.utility.waterTreatment.waste': 'Waste Water Treatment',
  'commercial.utility.waterTreatment.water': 'Water Treatment',
  'commercial.utility.oilGas': 'Gas / Oil Storage / Distribution',
  'commercial.utility.oilGas.gasGovernor': 'Gas Governor',
  'commercial.utility.oilGas.gasHolder': 'Gas Holder',
  'commercial.utility.oilGas.oilTerminal': 'Oil Terminal',
  'commercial.utility.other': 'Other Utility Use',
  'commercial.utility.other.cableTerminal': 'Cable Terminal Station',
  'commercial.utility.other.observatory': 'Observatory',
  'commercial.utility.other.radar': 'Radar Station',
  'commercial.utility.other.satelliteEarth': 'Satellite Earth Station',
  'commercial.utility.wasteManagement': 'Waste Management',
  'commercial.utility.publicPhone.box': 'Telephone Box',
  'commercial.utility.publicPhone.other': 'Other Public Telephones',
  'commercial.utility.dam': 'Dam',
  'commercial.emergency': 'Emergency / Rescue Service',
  'other.navigation.nautical.beacon': 'Nautical Navigation Beacon / Light',
  'other.navigation.road': 'Aid To Road Navigation',
  'other.navigation.guidePost': 'Guide Post',
  'other.coastal': 'Coastal Protection / Flood Prevention',
  'other.coastal.wall': 'Boulder Wall / Sea Wall',
  'other.coastal.floodGate': 'Flood Gate / Flood Sluice Gate / Flood Valve',
  'other.coastal.groyne': 'Groyne',
  'other.coastal.ripRap': 'Rip-Rap',
  'other.emergency': 'Emergency Support',
  'other.emergency.firstAid': 'Beach Office / First Aid Facility',
  'other.emergency.telephone': 'Emergency Telephone (Non Motorway)',
  'other.emergency.fire':
    'Fire Alarm Structure / Fire Observation Tower / Fire Beater Facility',
  'other.emergency.warning':
    'Emergency Equipment Point / Emergency Siren / Warning Flag',
  'other.emergency.lifeguard': 'Lifeguard Facility',
  'other.emergency.floatAids':
    'LIfe / Belt / Buoy / Float / Jacket / Safety Rope',
  'other.streetFurniture': 'Street Furniture',
  'other.agriculture': 'Agricultural Support Objects',
  'other.agriculture.fishPen': 'Fish Ladder / Lock / Pen / Trap',
  'other.agriculture.livestockPen': 'Livestock Pen / Dip',
  'other.agriculture.currick': 'Currick',
  'other.agriculture.slurry': 'Slurry Bed / Pit',
  'other.historic': 'Historical Site / Object',
  'other.historic.structure': 'Historic Structure / Object',
  'other.industrial': 'Industrial Support',
  'other.industrial.aditIncline': 'Adit / Incline / Level',
  'other.industrial.caissonDock': 'Caisson / Dry Dock / Grid',
  'other.industrial.channel': 'Channel / Conveyor / Conduit / Pipe',
  'other.industrial.chimney': 'Chimney / Flue',
  'other.industrial.crane': 'Crane / Hoist / Winch / Material Elevator',
  'other.industrial.flareStack': 'Flare Stack',
  'other.industrial.siloTank': 'Hopper / Silo / Cistern / Tank',
  'other.industrial.discharge':
    'Grab / Skip / Other Industrial Waste Machinery / Discharging',
  'other.industrial.kiln': 'Kiln / Oven / Smelter',
  'other.industrial.manholeShaft': 'Manhole / Shaft',
  'other.industrial.overflowSluiceValve':
    'Industrial Overflow / Sluice / Valve / Valve Housing',
  'other.industrial.coolingTower': 'Cooling Tower',
  'other.industrial.solarPanel': 'Solar Panel / Waterwheel',
  'other.industrial.pylon.telecom': 'Telephone Pole / Post',
  'other.industrial.pylon.electricity': 'Electricity Distribution Pole / Pylon',
  'other.natural': 'Significant Natural Object',
  'other.natural.tree': 'Boundary / Significant / Historic Tree / Pollard',
  'other.natural.rock': 'Boundary / Significant Rock / Boulder',
  'other.natural.hole': 'Natural Hole (Blow / Shake / Swallow)',
  'other.ornamental': 'Ornamental / Cultural Object',
  'other.ornamental.tomb': 'Mausoleum / Tomb / Grave',
  'other.ornamental.object': 'Simple Ornamental Object',
  'other.ornamental.maze': 'Maze',
  'other.leisure': 'Sport / Leisure Support',
  'other.leisure.hide': 'Butt / Hide',
  'other.leisure.gallop': 'Gallop / Ride',
  'other.leisure.modelRailway': 'Miniature Railway',
  'other.mail': 'Royal Mail Infrastructure',
  'other.mail.postBox': 'Postal Box',
  'other.mail.deliveryBox': 'Postal Delivery Box / Pouch',
  'other.mail.POBox': 'PO Box',
  'other.mail.additionalAddressee': 'Additional Mail / Packet Addressee',
  'other.scientific': 'Scientific / Observation Support',
  'other.scientific.meteo': 'Meteorological Station / Equipment',
  'other.scientific.radarSatellite': 'Radar / Satellite Infrastructure',
  'other.scientific.astronomy':
    'Telescope / Observation Infrastructure / Astronomy',
  'other.transport': 'Transport Support',
  'other.transport.cattleGridFord': 'Cattle Grid / Ford',
  'other.transport.stepsLiftEscalator': 'Elevator / Escalator / Steps',
  'other.transport.bridge': 'Footbridge / Walkway',
  'other.transport.post':
    'Pole / Post / Bollard (Restricting Vehicular Access)',
  'other.transport.subway': 'Subway / Underpass',
  'other.transport.customs': 'Customs Inspection Facility',
  'other.transport.layby': 'Lay-By',
  'other.transport.rail.crossing.vehicles': 'Level Crossing',
  'other.transport.mailPickUp': 'Mail Pick Up',
  'other.transport.rail.crossing.pedestrian': 'Railway Pedestrian Crossing',
  'other.transport.rail.buffer': 'Railway Buffer',
  'other.transport.rail.drag': 'Rail Drag',
  'other.transport.rail.infrastructure': 'Rail Infrastructure Services',
  'other.transport.rail.marker.km': 'Rail Kilometre Distance Marker',
  'other.transport.rail.lighting': 'Railway Lighting',
  'other.transport.rail.market.mile': 'Rail Mile Distance Marker',
  'other.transport.rail.turntable': 'Railway Turntable',
  'other.transport.rail.weighbridge': 'Rail Weighbridge',
  'other.transport.rail.signals': 'Rail Signalling',
  'other.transport.rail.traverse': 'Railway Traverse',
  'other.transport.goodsTramway': 'Goods Tramway',
  'other.transport.road.drag': 'Road Drag',
  'other.transport.road.vehicleDip': 'Vehicle Dip',
  'other.transport.road.turntable': 'Road Turntable',
  'other.transport.road.marker.mile': 'Road Mile Distance Marker',
  'other.transport.road.market.km': 'Road Kilometre Distance Marker',
  'other.transport.road.infrastructure': 'Road Infrastructure Services',
  'other.unsupported': 'Unsupported Site',
  'other.unsupported.cycleParking': 'Cycle Parking Facility',
  'other.unsupported.picnic': 'Picnic / Barbeque Site',
  'other.unsupported.travellingPersons': 'Travelling Persons Site',
  'other.unsupported.shelter': 'Shelter (Not Including Bus Shelter)',
  'parent.street': 'Street Record',
  residential: 'Residential',
  'residential.building': 'Ancillary Building',
  'residential.carParkingSpace': 'Car Park Space',
  'residential.carParkingSpace.allocated': 'Allocated Parking',
  'residential.dwelling': 'Residential dwelling',
  'residential.dwelling.caravan': 'Caravan',
  'residential.dwelling.house.detached': 'Detached',
  'residential.dwelling.house.semiDetached': 'Semi-detached',
  'residential.dwelling.house.terrace': 'Terrace',
  'residential.dwelling.flat': 'Flat',
  'residential.dwelling.boat': 'House Boat',
  'residential.dwelling.shelteredAccommodation': 'Sheltered Accommodation',
  'residential.dwelling.holiday': 'Privately Owned Holiday Caravan / Chalet',
  'residential.garage': 'Garage',
  'residential.garage.court': 'Lock-Up Garage / Garage Court',
  'residential.HMO': 'House In Multiple Occupation',
  'residential.HMO.parent': 'HMO Parent',
  'residential.HMO.bedsit':
    'HMO Bedsit / Other Non Self Contained Accommodation',
  'residential.HMO.undivided': 'HMO Not Further Divided',
  'residential.institution': 'Residential Institution',
  'residential.institution.care': 'Care / Nursing Home',
  'residential.institution.communal': 'Communal Residence',
  'residential.institution.noncommercial': 'Non-Commercial Lodgings',
  'residential.institution.religious': 'Religious Community',
  'residential.institution.education': 'Residential Education',
  unclassified: 'Unclassified',
  'unclassified.awaitingclassification': 'Awaiting Classification',
  'unclassified.pendingInvestigation': 'Pending Internal Investigation',
  dualUse: 'Dual Use',
  object: 'Object of Interest',
  'object.archaeological': 'Archaeological Dig Site',
  'object.monument': 'Monument',
  'object.monument.vertical': 'Obelisk / Milestone / Standing Stone',
  'object.monument.vertical.obelisk': 'Obelisk',
  'object.monument.vertical.standingStone': 'Standing Stone',
  'object.monument.memorial': 'Memorial / Market Cross',
  'object.monument.statue': 'Statue',
  'object.monument.ruin': 'Castle / Historic Ruin',
  'object.monument.other': 'Other Structure',
  'object.monument.other.boundaryStone': 'Boundary Stone',
  'object.monument.other.waterFeature': 'Cascade / Fountain',
  'object.monument.other.art': 'Permanent Art Display / Sculpture',
  'object.monument.other.windmill': 'Windmill (Inactive)',
  'object.statelyHome': 'Stately Home',
  'object.underground': 'Underground Feature',
  'object.underground.cave': 'Cave',
  'object.underground.hole': 'Pothole / Natural Hole',
  'object.underground.other': 'Other Underground Feature',
  'object.underground.other.cellar': 'Cellar',
  'object.underground.other.extraction': 'Disused Mine',
  'object.underground.other.extraction.mine': 'Mineral Mining / Inactive',
  'object.underground.other.extraction.oilGas':
    'Oil And / Gas Extraction/ Inactive',
  'object.underground.other.extraction.quarry':
    'Mineral Quarrying And / Open Extraction / Inactive',
  'object.underground.other.water': 'Well / Spring',
  'object.underground.other.water.spring': 'Spring',
  'object.underground.other.water.well': 'Well',
  'object.religious': 'Place Of Worship',
  'object.religious.building': 'Religious building',
  'object.religious.building.abbey': 'Abbey',
  'object.religious.building.cathedral': 'Cathedral',
  'object.religious.building.church': 'Church',
  'object.religious.building.chapel': 'Chapel',
  'object.religious.building.gurdwara': 'Gurdwara',
  'object.religious.building.kingdomHall': 'Kingdom Hall',
  'object.religious.building.lychGate': 'Lych Gate',
  'object.religious.building.mosque': 'Mosque',
  'object.religious.building.minster': 'Minster',
  'object.religious.building.stupa': 'Stupa',
  'object.religious.building.synagogue': 'Synagogue',
  'object.religious.building.temple': 'Temple',
};
