/**
 * Values for data.property.use
 */
export const ExistingUses = {
  'commercial.advert': 'Display an advert',
  'commercial.leisure.holiday.camping': 'Campsite or caravan park',
  'commercial.leisure.sport': 'Sports',
  'commercial.leisure.sport.clayPigeon': 'Clay pigeon shooting',
  'commercial.leisure.sport.equestrian': 'Keeping horses',
  'commercial.leisure.sport.firearms': 'Firearms',
  'commercial.leisure.sport.motorRacing': 'Motor racing',
  'commercial.leisure.sport.running': 'Running race',
  'commercial.leisure.sport.warGame': 'War game',
  'commercial.storageLand': 'Storage land',
  'commercial.temporary': 'Temporary market',
  'land.agriculture': 'Agriculture',
  'land.allotment': 'Allotment',
  'land.natural': 'Natural landscape',
  'land.unused.vacant': 'Vacant land',
  'residential.garden': 'Garden of a home',
};

/**
 * Values for data.proposal.use
 */
export const ProposedUses = {
  business: 'Offices or R&D lab',
  'changeOfUse.commercial.advert': 'Display an advert',
  'changeOfUse.commercial.leisure.holiday.camping': 'Campsite or caravan park',
  'changeOfUse.commercial.leisure.sport': 'Sports',
  'changeOfUse.commercial.leisure.sport.clayPigeon': 'Clay pigeon shooting',
  'changeOfUse.commercial.leisure.sport.equestrian': 'Keeping horses',
  'changeOfUse.commercial.leisure.sport.firearms': 'Firearms',
  'changeOfUse.commercial.leisure.sport.motorRacing': 'Motor racing',
  'changeOfUse.commercial.leisure.sport.running': 'Running race',
  'changeOfUse.commercial.leisure.sport.warGame': 'War game',
  'changeOfUse.commercial.storageLand': 'Storage land',
  'changeOfUse.commercial.temporary': 'Temporary market',
  'changeOfUse.land.agriculture': 'Agriculture',
  'changeOfUse.land.allotment': 'Allotment',
  'changeOfUse.land.natural': 'Natural landscape',
  'changeOfUse.land.unused.vacant': 'Vacant land',
  'changeOfUse.residential.garden': 'Garden of a home',
  'institutions.school': 'School',
  leisure: 'Leisure',
  'leisure.betting': 'Betting shop',
  retail: 'Shop',
  'retail.carShowroom': 'Vehicle showroom',
  'retail.dryCleaner': 'Dry cleaner',
  'retail.funeral': 'Funeral parlour',
  'retail.hairdresser': 'Hairdresser',
  'retail.hire': 'Hire shop',
  'retail.internet': 'Internet cafe',
  'retail.laundrette': 'Laundrette',
  'retail.petrolStation': 'Petrol station',
  'retail.postOffice': 'Post office',
  'retail.restaurants': 'Restaurants',
  'retail.services': 'Financial or professional service',
  'retail.services.accounting': 'Accountancy service',
  'retail.services.bank': 'Bank',
  'retail.services.buildingSociety': 'Building society',
  'retail.services.carHire': 'Vehicle hire location',
  'retail.services.employmentAgency': 'Employment agency',
  'retail.services.estateAgent': 'Estate agent',
  'retail.services.legal': 'Legal service',
  'retail.services.payDayLoans': 'Pay day loan shop',
  'retail.services.taxi': 'Taxi office',
  'retail.shop.food': 'Food or grocery shop (including off licenses)',
  'retail.shop.other': 'Another type of shop',
  'retail.takeaway': 'Hot food takeaway, bakery or delicatessen',
  'retail.travel': 'Travel agent',
  'retail.warehouse': 'Retail warehouse',
};
