import {File} from './schema/File';
import {Metadata} from './schema/Metadata';
import {PreAssessment} from './schema/PreAssessment';
import {Responses} from './schema/Responses';
import {Applicant} from './schema/data/Applicant';
import {Application} from './schema/data/Application';
import {FilesAsData} from './schema/data/Files';
import {Property} from './schema/data/Property';
import {Proposal} from './schema/data/Proposal';
import {User} from './schema/data/User';

/**
 * @title Digital Planning Application
 * @description The root specification for a planning application in England generated by a digital planning service
 */
export interface Schema {
  data: {
    application: Application;
    user: User;
    applicant: Applicant;
    property: Property;
    proposal: Proposal;
    files?: FilesAsData;
  };
  preAssessment?: PreAssessment;
  responses: Responses;
  files: File[];
  metadata: Metadata;
}
