import {File} from './File';
import {Metadata} from '../../shared/Metadata';
import {PreAssessment} from './PreAssessment';
import {Responses} from '../../shared/Responses';
import {Applicant} from './data/Applicant';
import {ApplicationData} from './data/ApplicationData';
import {FilesAsData} from './data/Files';
import {Property} from './data/Property';
import {Proposal} from './data/Proposal';
import {User} from './data/User';

/**
 * @title Application
 * @description The root specification for a planning application in England generated by a digital planning service
 */
export interface Application {
  data: {
    application: ApplicationData;
    user: User;
    applicant: Applicant;
    property: Property;
    proposal: Proposal;
    files?: FilesAsData;
  };
  preAssessment?: PreAssessment;
  responses: Responses;
  files: File[];
  metadata: Metadata;
}
