import {PrimaryApplicationTypes} from '../digitalPlanningApplication/enums/ApplicationTypes';
import {User} from './User';

interface GenericApplication<T extends PrimaryApplicationTypes> {
  primaryApplicationType: T;
  data: {
    user: User<T>;
  };
}

/**
 * @description Application for a "Planning Permission" project
 */
export type PlanningPermissionApplication = GenericApplication<'pp'>;

/**
 * @description Application for a "Prior Approval" project
 */
export type PriorApprovalApplication = GenericApplication<'pa'>;

/**
 * @description Application for a "Works to trees" project
 */
export type WorksToTreesApplication = GenericApplication<'wtt'>;

/**
 * @title App
 * @description The root specification for a planning application in England generated by a digital planning service
 */
export type App =
  | PlanningPermissionApplication
  | PriorApprovalApplication
  | WorksToTreesApplication;
