import {PlanXMetadata} from '../../shared/Metadata';
import {Responses} from '../../shared/Responses';
import {User} from '../../shared/User';
import {File} from '../application/File';
import {PreApplicant} from './data/Applicant';
import {PreApplicationData} from './data/ApplicationData';
import {Property} from './data/Property';
import {Proposal} from './data/Proposal';

/**
 * @title PreApplication
 * @description The root specification for a planning pre-application in England generated by a digital planning service
 */
export interface PreApplication {
  data: {
    application: PreApplicationData;
    user: User;
    applicant: PreApplicant;
    property: Property;
    proposal: Proposal;
  };
  responses: Responses;
  files: File[];
  metadata: PlanXMetadata;
}
