import {Metadata} from '../../shared/Metadata';
import {Responses} from '../../shared/Responses';
import {Applicant} from '../application/data/Applicant';
import {ApplicationData} from '../application/data/ApplicationData';
import {Property} from '../application/data/Property';
import {Proposal} from '../application/data/Proposal';
import {User} from '../application/data/User';

/**
 * @title PreApplication
 * @description The root specification for a pre-planning application in England generated by a digital planning service
 */
export interface PreApplication {
  data: {
    application: ApplicationData;
    user: User;
    applicant: Applicant;
    property: Property;
    proposal: Proposal;
  };
  responses: Responses;
  files: File[];
  metadata: Metadata;
}
