import {File} from './File';
import {Metadata} from './Metadata';
import {PreAssessment} from './PreAssessment';
import {Responses} from './Responses';
import {Applicant} from './data/Applicant';
import {Application} from './data/Application';
import {FilesAsData} from './data/Files';
import {Property} from './data/Property';
import {Proposal} from './data/Proposal';
import {User} from './data/User';

/**
 * @title Digital Planning Application
 * @description The root specification for a planning application in England generated by a digital planning service
 */
export interface DigitalPlanningApplication {
  data: {
    application: Application;
    user: User;
    applicant: Applicant;
    property: Property;
    proposal: Proposal;
    files?: FilesAsData;
  };
  preAssessment?: PreAssessment;
  responses: Responses;
  files: File[];
  metadata: Metadata;
}
