import {GeoBoundary} from '../../shared/Boundaries';
import {PlanXMetadata} from '../../shared/Metadata';
import {Responses} from '../../shared/Responses';
import {File} from '../application/File';
import {Complainant} from './data/Complainant';

/**
 * @title Enforcement
 * @description The root specification for an enforcement report in England generated by a digital planning service
 */
export interface Enforcement {
  data: {
    application: {
      type: {
        value: 'breach';
        description: 'Report a planning breach';
      };
    };
    complainant: Complainant;
    property: {
      // TODO - relies on PR #353
    };
    proposal: {
      boundary: GeoBoundary;
    };
  };
  responses: Responses;
  files?: File[];
  metadata: PlanXMetadata;
}
