import {Responses} from '../../shared/Responses';
import {Applicant} from './data/Applicant';
import {ApplicationData} from './data/ApplicationData';
import {Property} from './data/Property';
import {Proposal} from './data/Proposal';
import {UserBase} from './data/User';
import {ApplicationType} from './enums/ApplicationType';
import {File} from './File';
import {PrototypePlanXMetadata} from './Metadata';
import {PreAssessment} from './PreAssessment';

/**
 * @internal
 * The generic base type for all applications
 * Child properties may differ based on a granular application type parameter
 */
interface ApplicationSpecification<T extends ApplicationType> {
  applicationType: T;
  data: {
    user: UserBase;
    applicant: Applicant<T>;
    application: ApplicationData<T>;
    property: Property<T>;
    proposal: Proposal<T>;
  };
  preAssessment?: PreAssessment;
  responses: Responses;
  files: File[];
  metadata: PrototypePlanXMetadata;
}

export type AdvertConsent = ApplicationSpecification<'advertConsent'>;
export type ComplianceConfirmation = ApplicationSpecification<'complianceConfirmation'>;
export type HedgerowRemovalNotice = ApplicationSpecification<'hedgerowRemovalNotice'>;
export type LandDrainageConsent = ApplicationSpecification<'landDrainageConsent'>;
export type LDCBreachOfCondition = ApplicationSpecification<'ldc.breachOfCondition'>;
export type LDCExisting = ApplicationSpecification<'ldc.existing'>;
export type LDCListedBuildingWorks = ApplicationSpecification<'ldc.listedBuildingWorks'>;
export type LDCProposed = ApplicationSpecification<'ldc.proposed'>;
export type ListedBuildingConsent = ApplicationSpecification<'listed'>;
export type PriorApproval = ApplicationSpecification<'pa'>;
export type PPFullHouseholder = ApplicationSpecification<'pp.full.householder'>;
export type PPFullHouseholderRetro = ApplicationSpecification<'pp.full.householder.retro'>;
export type WTTConsent = ApplicationSpecification<'wtt.consent'>;
export type WTTNotice = ApplicationSpecification<'wtt.notice'>;
// TODO: All the rest!

/**
 * @title PrototypeApplication
 * @description The (prototype) root specification for a planning application in England generated by a digital planning service
 */
export type PrototypeApplication =
  | AdvertConsent
  | ComplianceConfirmation
  | HedgerowRemovalNotice
  | LandDrainageConsent
  | LDCBreachOfCondition
  | LDCExisting
  | LDCListedBuildingWorks
  | LDCProposed
  | ListedBuildingConsent
  | PriorApproval
  | PPFullHouseholder
  | PPFullHouseholderRetro
  | WTTConsent
  | WTTNotice;
