/**
 * File types
 */
export const FileTypes = {
  'property.drawing.elevation': 'Elevation plan - existing',
  'property.drawing.floorPlan': 'Floor plan - existing',
  'property.drawing.roofPlan': 'Roof plan - existing',
  'property.drawing.section': 'Section - existing',
  'property.drawing.sitePlan': 'Site plan - existing',
  'property.drawing.usePlan': 'Use plan - existing',
  'property.photograph': 'Photographs',
  'property.site.locationPlan': 'Location plan',
  'proposal.drawing.elevation': 'Elevation plan - proposed',
  'proposal.drawing.floorPlan': 'Floor plan - proposed',
  'proposal.drawing.other': 'Other - drawing',
  'proposal.drawing.roofPlan': 'Roof plan - proposed',
  'proposal.drawing.section': 'Section - proposed',
  'proposal.drawing.sitePlan': 'Site plan - proposed',
  'proposal.drawing.unitPlan': 'Unit plan - proposed',
  'proposal.drawing.usePlan': 'Use plan - proposed',
  'proposal.document.bankStatement': 'Bank statement',
  'proposal.document.buildingControl.certificate':
    'Building control certificate',
  'proposal.document.construction.invoice': 'Construction invoice',
  'proposal.document.contamination': 'Contamination report',
  'proposal.document.councilTaxBill': 'Council tax bill',
  'proposal.document.declaration': 'Statuatory declaration',
  'proposal.document.designAndAccess': 'Design and Access Statement',
  'proposal.document.floodRisk': 'Flood risk assessment',
  'proposal.document.heritageStatement': 'Heritage Statement',
  'proposal.document.noise': 'Noise assessment',
  'proposal.document.other': 'Other - document',
  'proposal.document.other.evidence': 'Other - correspondence',
  'proposal.document.sunAndDaylight': 'Sunlight and daylight report',
  'proposal.document.tenancyAgreement': 'Tenancy agreement',
  'proposal.document.tenancyInvoice': 'Tenancy invoice',
  'proposal.document.transport': 'Transport assessment',
  'proposal.document.utility.bill': 'Utility bill',
  'proposal.photograph': 'Photographs',
  'proposal.visualisation': 'Visualisations',
};
