#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" != "main" ]; then
	pnpm build-json-examples
  pnpm build-schema:dev
fi

pnpm check && pnpm fix
git add .
